### ISSUE TITLE
New entity string ID being stored as integer

### ISSUE THREAD

**Issue by micaww** [sebelga/gstore-node#1]
For one of my kinds, I store custom string as the ID in the format of "user1:user2" (where user1 and user2 are numerical IDs) for easy and fast retrieving. To create this string, I'm using `util.format` and passing it to the second parameter of a new model instance. When I save this to the datastore and check to see how it saved, it shows only "user1" as a numerical ID. How can I force gstore to save the ID as a string even though one is passed to the new instance?

For now, I'm saving through gcloud which works fine.

**Comment by sebelga** [comment]
It seems to be a bug, thanks for reporting it.
Let me have a look at it. Can you confirm that your id is something like this: 
"235207494:246457356"

**Comment by micaww** [comment]
That is correct. Just to clarify, if I send your string through gstore-node, "235207494:246457356", datastore will show "id=235207494". But if I send through gcloud, it shows "name=235207494:246457356".

Thank you. Great module.

**Comment by sebelga** [comment]
I just released a version with a fix that should also set entityKey.name to your string id. Try it and tell me if it works now for you.
Thank you for the feedback!

**Comment by micaww** [comment]
Works beautifully, thank you. I converted to gstore-node on a project with very complex data, and have found a couple of other little things. Once I remember them, I'll create issues for you.

**Comment by sebelga** [comment]
Great, thank you. All the feedback is welcome :)
