### ISSUE TITLE
Docs wrong about unspecified properties not being saved

### ISSUE THREAD

**Issue by StephenCarboni** [sebelga/gstore-node#103]
ref: https://sebelga.gitbooks.io/gstore-node/content/schema/

>With this simple schema, if you try to save an entity with any other property than the ones defined here, it won't validate and won't be saved in the Datastore.
>Guaranteed! :)

This is not what happens. I must call sanitize with my data first before passing it to the model constructor and saving.

**Comment by sebelga** [comment]
Hello,
You don't have to call `sanitize()` before passing it to the constructor. If you don't pass it, and then try to save the entity, an error will be thrown.
If this does not happen, please share your code, thanks!

**Comment by StephenCarboni** [comment]
Hi,

I think I know what the issue may be. I'm saving the entities in batches of 500 through `gstore.save()`. I thought of this when I realised the entities are not validating through this method either.

Look at the code, it seems to be the case that the entities are just saved as is:
https://github.com/sebelga/gstore-node/blob/b80290a9136a772fd2abbc52351189133944a2f2/lib/index.js#L113

**Comment by sebelga** [comment]
Yes with the global `gstore.save()` method there is no validation. It makes me think that validation could also be done there. It will add a small overhead so I would probably leave it as optional.
I will try to add it in the next release.

**Comment by sebelga** [comment]
Hello,
I just made release v4.2.0 that has accepts a configuration object to validate the entities before saving.
Let me know if it works for you 👍
