### ISSUE TITLE
Incorrect Joi schema for object nesting > 1 level deep.

### ISSUE THREAD

**Issue by glenpike** [sebelga/gstore-node#104]
We're using Joi to create our schema's and we have run into an issue with anything nested more than one level deep.

We're using [Joi.describe()](https://github.com/hapijs/joi/blob/v13.2.0/API.md#describeschema) to provide the schema structure so we can reduce this to a set of dot-notation paths for the schema.  For example, the following schema:

```
{
    survey: {
        joi: Joi.object().keys({
            id: Joi.string().guid().required(),
            name: Joi.string().required(),
        }),
    },
    completedAt: {
        joi: Joi.date(),
    },
    assigned: {
        joi: Joi.object().keys({
            to: {
                joi: Joi.object().keys({
                    id: Joi.string().guid().required(),
                    email: Joi.string().required(),
                }),
            },
        }),
    },
}
```
Should include the 'paths':
```
survey.id
completedAt,
assigned.to.id
```
When we use gstore-node to create the Schema, then extract it with Joi.describe, we end up with a structure that has extra 'children' for the ;assigned' _tree_ - see below:
```
{
    "type": "object",
    "children": {
        "survey": {
            "type": "object",
            "children": {
                "id": {
                    "type": "string",
                    "flags": {
                        "presence": "required"
                    },
                    "invalids": [""],
                    "rules": [{
                        "name": "guid"
                    }]
                },
                "name": {
                    "type": "string",
                    "flags": {
                        "presence": "required"
                    },
                    "invalids": [""]
                }
            }
        },
        "completedAt": {
            "type": "date"
        },
        "assigned": {
            "type": "object",
            "children": {
                "to": {
                    "type": "object",
                    "children": {
                        "joi": {
                            "type": "object",
                            "children": {
                                "id": {
                                    "type": "string",
                                    "flags": {
                                        "presence": "required"
                                    },
                                    "invalids": [""],
                                    "rules": [{
                                        "name": "guid"
                                    }]
                                },
                                "email": {
                                    "type": "string",
                                    "flags": {
                                        "presence": "required"
                                    },
                                    "invalids": [""]
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

This actually gives us the path 'assigned.to.joi.id' which is inconsistent with the other 2 paths.

See the code in Runkit for an example of how we do this: https://runkit.com/glenpike/gstore-node-nested-joi-schema-issue  (damned if I can get Runkit to work more than once, but it runs fine in the terminal on my machine).

**Comment by sebelga** [comment]
Hi,
Thanks for reporting this. I haven't tested this use case and will look into it. But the first question is: does it validate correctly? 😄 
I can guess why the schema described adds this "children" and will see how I could flatten it. But what exactly are you trying to achieve?
cheers

**Comment by glenpike** [comment]
Hi, thanks for the reply. I've not tested if that schema validates. It's a cut down version of the real-world use case.
We reduce the output from describe to a set of 'dot-notation' paths that we can use to validate queries from requests, e.g.

`GET /something?assigned.to.email=me@example.com`

Is valid, but the paths shouldn't include the 'joi' keys

**Comment by sebelga** [comment]
I am not sure I follow what you are trying to achieve. I would need a more real example.  But from what I understand, it seems that you don't need gstore-node Schema for your validation. Create your Joi schema and validate the request query value against it.

The validation of gstore-node occurs while saving or calling validate() so in your example it would be something like

```js
// model declaration
const schema = new Schema({
    survey: {
        joi: Joi.object().keys({
            id: Joi.string().guid().required(),
            name: Joi.string().required(),
        }),
    },
    completedAt: {
        joi: Joi.date(),
    },
    assigned: {
        joi: Joi.object().keys({
            to: {
                joi: Joi.object().keys({
                    id: Joi.string().guid().required(),
                    email: Joi.string().required(),
                }),
            },
        }),
    },
});

const Survey = gstore.model('Survey', schema);
```

```js
// route handler
const Survey = require('./models/survey.model');

const somethingHandler = (req, res) => {
    const entityData = {
        survey: {
            id: 123,
            name: 'survey-name'
        },
        completedAt: new Date(),
        assigned: {
            to: {
                id: 123,
                email: req.query['assigned.to.email']
            }
        }
    };
    const survey = new Survey(entityData)
    survey.save()
        .then()
        .catch((err) => {
            // validation error are here
        })
};
```

So if your endpoint `/something` does not receive a query param `assigned.to.email` the entity won't validate and won't be saved.

**Comment by sebelga** [comment]
Hi @glenpike do you still need help on this? Should I look into it or you managed to make it work?
thanks

**Comment by glenpike** [comment]
Hi, Okay, we're not using the endpoint as a POST for create / update, but I might look into this as a possibility for what we're trying to do - we have a generic 'list' endpoint which we can query for properties matching certain values and we're using the schema to check if the queries are 'valid', e.g. match the model schema.  I've not had a change to check this because we've been too busy, so by all means, close the bug and it it's still relevant, I can reopen (if that's okay?)

**Comment by sebelga** [comment]
Ok, I see now what you are trying to do. We can leave the issue opened, I will label it as an improvement and will see how I can generate a correct Joi from its  `describe` method. thanks.

**Comment by sebelga** [comment]
Hi,
I will close this issue as I won't be able to work on it. Feel free to open a PR if you have a way to solve this.

Asside, now that I read your snippet again, I wonder if you didn't make a mistake:

```js
// this...
assigned: {
  joi: Joi.object().keys({
      to: {
          joi: Joi.object().keys({
              id: Joi.string().guid().required(),
              email: Joi.string().required(),
          }),
      },
  }),
},

// should maybe be this
assigned: {
  joi: Joi.object().keys({
      to: Joi.object().keys({
        id: Joi.string().guid().required(),
        email: Joi.string().required(),
    }),
  }),
},

```
