### ISSUE TITLE
alias other datastore batch methods

### ISSUE THREAD

**Issue by StephenCarboni** [sebelga/gstore-node#105]
`gstore.save()` is not upserting, but datastore.upsert is.

Maybe allow `{  method: 'upsert|insert|update' }` option like `Entity.save()` has?

Ref: https://cloud.google.com/datastore/docs/concepts/entities#batch_operations

**Comment by sebelga** [comment]
Hi,
Good point, I will add this along with the #103 enhancement. Sorry for the delay on the issues I am working on gstore-cache this week. Hopefully next week I can make a release with all the upgrades 👍

**Comment by sebelga** [comment]
Hello,
I just made release v4.2.0 that has now a configuration object where you can define the save method.
Let me know if it works for you 👍
