### ISSUE TITLE
Update object containing array return error

### ISSUE THREAD

**Issue by nexussmart** [sebelga/gstore-node#111]
Hi,
When we update data with type object who contains array , the function update returns undefined and data are not update in datastore.

**Comment by sebelga** [comment]
Hi,
Could you show the Schema + the code you use to update the entity so I can replicate?
thanks

**Comment by sebelga** [comment]
Sorry but you mix "TestModel", "TestStore"... I am not seeing it clearly. Also you dont need to use defer as the udpate function return already a Promise.  
Is this what you are trying to do?

```js
const gstore = require('gstore-node')();
const { Schema } = gstore;

const testSchema = new Schema({
    testData : { type: Object, optional: true, excludeFromIndexes: true },
    state: { type: Number, required: true }
});

const Model = gstore.model('Test', testSchema);

const updateTest= (id, data) => {
    const entityData = Model.sanitize(data);

    // No need to defer as "update" already returns a Promise
    return Model.update(id, entityData)
        .then((entity) => entity.plain());
};

const data = {
    state: 1,
    testData: {
        field1: "test",
        field2: [ { field: "test"} ]
    }
}

// Passing id "123"
updateTest(123, data);

```

**Comment by nexussmart** [comment]
export const TestStore = gstore.model("Test", testSchema);

(data: TestModel) => it's my model between front and back

**Comment by sebelga** [comment]
I just wrote a test and I cann't reproduce your error. The following test passes:

```js
const chai = require('chai');
const gstore = require('gstore-node')();

const { assert, expect } = chai;
const { Schema } = gstore;

const testSchema = new Schema({
    testData: { type: Object, optional: true, excludeFromIndexes: true },
    state: { type: Number, required: true },
});

const TestModel = gstore.model('Test', testSchema);

const updateTest = (id, data) => {
    const entityData = TestModel.sanitize(data);

    return TestModel.update(id, entityData)
        .then(entity => entity.plain());
};

const test = new TestModel({ state: 0 }, 123);

test.save()
    .then(() => {
        const data = {
            state: 1,
            testData: {
                field1: 'test',
                field2: [{ field: 'test' }],
            },
        };
        return updateTest(123, data)
            .then((entity) => {
                assert.isDefined(entity.testData.field2);
                expect(entity.testData.field2).deep.equal([{ field: 'test' }]);
            });
    });
```

Does this work on your side?

**Comment by nexussmart** [comment]
hi,
It's work. My problem was the type in schema.
My schema  :
const testSchema = new Schema({
    testData: { type: "**object**", optional: true, excludeFromIndexes: true },
    state: { type: "number", required: true },
});

your:
const testSchema = new Schema({
    testData: { type: **Object**, optional: true, excludeFromIndexes: true },
    state: { type: Number, required: true },
});

Thanks !!

**Comment by sebelga** [comment]
No problem, happy to help. I'll close the issue then.
