### ISSUE TITLE
Gitbook should link here

### ISSUE THREAD

**Issue by trollkotze** [sebelga/gstore-node#112]
Hello!

Not an issue with this repo in itself. But I just come from the [GitBook](https://sebelga.gitbooks.io/gstore-node) and was looking around for a quick link to click to get here, and there was none.
I think there might be not a single link to this repository in the entire GitBook. Would certainly make it easier for people to find the right place for feedback, questions and issues!

:nose:

**Comment by sebelga** [comment]
Hi!
Sorry for such a long delay :) You're totally right and I will update the doc in Gitbook. I was thinking that people would go from here to Gitbook and not the other way around.

Thanks for the feedback! :+1:
