### ISSUE TITLE
filtering nested values with order

### ISSUE THREAD

**Issue by donking13** [sebelga/gstore-node#113]
> Error: no matching index found. recommended index is:
- kind: stories_data
  properties:
  - name: inspiration_tagging.categoryId
  - name: location_tagging.locId
  - name: updated_date
    direction: desc

I caught this error when even I filter with nested values and add ordering to it.

```
filters:
0:(2) ["inspiration_tagging.categoryId", "5710606233501696"]
1:(2) ["location_tagging.locId", "5631383682678784"]
format:"JSON"
limit:8
order:{property: "updated_date", descending: true, ascending: false}
start:""
```

for some reason, it doesn't let me order when the query is filtered, is it really that way?

**Comment by sebelga** [comment]
Hi,
You probably did not create the index.
Please refer to this issue to see how to do it: https://github.com/sebelga/gstore-node/issues/74

Let me know if you still have problems.

**Comment by sebelga** [comment]
Hello,
Did you manage to add the indexes? Can I close the issue?

**Comment by donking13** [comment]
Yes i did, thank you!

**Comment by sebelga** [comment]
Great! 👍
