### ISSUE TITLE
Possible issue with Dataloader

### ISSUE THREAD

**Issue by glenpike** [sebelga/gstore-node#114]
Hi,

Been using your library for a while now - my colleague has done most of the abstraction work, but enjoying learning the stuff as I go.  Great job & thanks!

Our application where we've previously batch the number of id's we pass to Model.get when the length of id's goes over 1000 - as we hit limits with the DataStore.

We've just turned the Dataloader on recently and now we are seeing a lot of errors in our logs:
`3 INVALID_ARGUMENT: cannot get more than 1000 keys in a single call`

Does the Dataloader wrapper https://github.com/sebelga/gstore-node/blob/1105185a66056c9f15d60e63bf171f54e2e2451a/lib/dataloader.js#L23 need to limit [batch size too](https://github.com/facebook/dataloader#new-dataloaderbatchloadfn--options), or is there some workaround we need to do to work with Dataloader and getting > 1000 keys?

**Comment by glenpike** [comment]
So as a crude hack, I amended that file in my node_modules:

https://github.com/sebelga/gstore-node/blob/1105185a66056c9f15d60e63bf171f54e2e2451a/lib/dataloader.js#L32 changed to
```
), { cacheKeyFn: _key => keyToString(_key), maxBatchSize: 1000 });
```

Which seemed to sort things out.

Sorry, I'm not in a position to do a tested PR for this right now.  I could push a PR with just the change, but testing would take a while for me to suss out and do I think :(

**Comment by sebelga** [comment]
Hi,
Thanks for the kind words!
I was in the middle of answering when I see your second message :smile: 
I didn't know about the maxBatchSize property. Will it do recursive calls to fetch all the keys? Would that work for you?

**Comment by glenpike** [comment]
Whatever it does, adding that in seems to work for me - I haven't taken the time to fully understand it.

**Comment by glenpike** [comment]
Okay, I think I found it - here: https://github.com/facebook/dataloader/blob/master/src/index.js#L236 - so it looks like it just creates multiple promises for each chunk.

**Comment by sebelga** [comment]
Great! Thanks for looking into this. I will add the maxBatchSize limitation then. Hope to make a release soon with it 👍

**Comment by sebelga** [comment]
Hi, I just release v4.2.2 with this fix. Thanks for reporting! 👍
