### ISSUE TITLE
Performing IN or OR operations?

### ISSUE THREAD

**Issue by jeffj6123** [sebelga/gstore-node#117]
Does this library provide support to simulate or possibly handle having these performed for filters in queries? I know that its not natively implemented in the node js cloud datastore library and was wonder if there was a way to handle it here? I know as of right now you dont support a list value when performing a filter against a property.

**Comment by sebelga** [comment]
In your example, why don't you use ancestor entity for the User and the Posts as children of each User? Then you can make 1 query by ancestor and limit + ordering

**Comment by sebelga** [comment]
Hello,
Did you give some thoughts about my last comment? Would that solution work for you? It would be definitely a more efficient query than making multiple queries.

**Comment by jeffj6123** [comment]
Hey, yeah we looked into it and eventually considered switching to mongo to allow some more flexibility in regard to some other decisions weve made. Thank you though
