### ISSUE TITLE
Typescript definition file incomplete

### ISSUE THREAD

**Issue by huysamen** [sebelga/gstore-node#118]
The TS definition files' `get` method only allows for a single response `Promise<Entity<T> & { [P in keyof T]: T[P] }>` however multiple IDs can be passed to the `get` method which would return an array of results.

**Comment by sebelga** [comment]
Hi!
Thanks for reporting, I saw a few other mistakes in the Typescript definition file and I am in the middle of updating it. Got caught by the holidays 😄 I will try to fix it asap. 👍

**Comment by huysamen** [comment]
Great, thanks!

**Comment by sebelga** [comment]
Hi,
Sorry for the long wait. I just released v4.2.6 with a few fixes (and this one) on the Typescript definition file. I close the issue for now, feel free to reopen it if the problem persists.  👍

**Comment by huysamen** [comment]
Hi, thanks for the update.  While the TS definitions file seems much better now thanks,  it is still not correct unfortunately.  Or should I rather say, it will not work as I think you expect it might (**_it may in the future_**).  The problem comes in that you are trying to use conditional return types.  While the TS language is perfectly happy with you doing that syntactically, it does not **yet** work.

When you use the return type `Promise<U extends Array<any> ? Entity<T>[] : Entity<T>>` for the `get()`, TS will just always expect the variable to be assigned to a variable of type `Entity<T>[] | Entity<T>`, because it cannot see the outcome of the condition **yet**.  I use 'yet' often here, because this is a current open feature request as you can see [here](https://github.com/Microsoft/TypeScript/issues/24929) and [here](https://github.com/Microsoft/TypeScript/issues/22735).

I think the best here is to either always return an array like the standard Datastore libraries (I am not particularly fond of that approach), or have 2 separate functions, one for reading multiple, and one for reading a single entity.

**Comment by sebelga** [comment]
Hi, thanks for the feedback but do you have a usecase where it does not work?

I did make a few trials and it worked on my side (with Typescript `2.9.2`). Concretely here:
https://github.com/sebelga/google-datastore-blog-app/blob/typescript-version/src/server/modules/blog/blog-post/blog-post.db.ts#L87
If I pass an array of `number` as `id`, then `entity` returned is an Array of `Entity<T>`. If I pass just a number, then entity is a single `Entity<T>`.

About what you say: returning always an array would create a breaking change. I also thought about adding another function to get multiple keys (`getMany()`) but as it was working (at least in my trials) I did not bother.

Could you provide a example where it does not work?

**Comment by sebelga** [comment]
This is strange, can you confirm that DS.int() casts to "number"?

This is what I have on my side:

![screenshot-1](https://user-images.githubusercontent.com/2854616/44667026-01bf8380-aa1a-11e8-9778-3d66d953a70e.jpg)
![screenshot-2](https://user-images.githubusercontent.com/2854616/44667034-05530a80-aa1a-11e8-8627-d51d15b9f8f1.jpg)

You can see that if I pass an Array entity is an Array, otherwise not.
I will make a try with Typescript 3 to see if it behaves differently

**Comment by huysamen** [comment]
No, `DS.int()` results in a DataStore-native object.  It is used to represent large numbers in Javascript, since JS numbers are not actually 64bit.  It can actually just hold 2^53-1.  This is a problem, especially in integrated systems like ours where we have interoperability between systems with Java that uses `long`s (which are properly 64bit).  Think something like a Tweet ID.  Javascript cannot store that as a `number`, however Java can as a `long`.

The overcome this the DataStore library offers the `datastore.int()` method, which it knows to translate into its `Integer` type (which again is also properly 64bit).

This is also a bigger problem though, since reading those values from DataStore (even with the standard library) results in values being truncated.  I have an [open issue](https://github.com/googleapis/nodejs-datastore/issues/147) with the Google team regarding this.

**Comment by sebelga** [comment]
Hello,
Yes I know that DS.int() results in a string but I was wondering its cast in Typescript. I just saw it was `DatastoreInt`
I am on holiday until next Monday so not much time to look into this but I made a trial and you should get a Typescript error when you cast it (I will add a fix to support DatastoreInt in the `get()` method.

So for now can you try to cast it to string?

```js
// no need to set the type to `account`, it will be set automatically
const account = await Accounts.get(<string> DS.int(data.accountId));
```

If this does not work, then I need to try wth Typescript 3. cheers 👍

**Comment by sebelga** [comment]
Hello,
I just made a trial with Typescript 3 and I got it working.
This is the test file I created

```ts
import Gstore, { Entity } from 'gstore-node';

const gstore = Gstore();
const { Schema } = Gstore;

type UserType = {
    name: string;
    age: number;
}

const schema = new Schema<UserType>({
    name: { type: String },
    age: { type: Number },
});

const User = gstore.model('User', schema);

const getUser = async(id: string) => {
    const user: Entity<UserType> = await User.get(id);
    console.log(user.age);

    const users: Entity<UserType>[] = await User.get([123, 456]);
    users.forEach((user) => {
        console.log(user.age);
    });
}
```

Could you try it on your side and let me know if it works for you?
Thanks

**Comment by huysamen** [comment]
It seems good now.  I think our problem came in because we made a type alias:

```
type UserSchema = {
    name: string;
    age: number;
}

const schema = new Schema<UserSchema>({
    name: { type: String },
    age: { type: Number },
});

export type User = Entity<UserSchema>;
export const Users: Model<UserSchema> = gstore.model<UserSchema>('User', schema);
```

this allowed us a more natural linguistic flow of:

```
const user: User = await Users.get(123);
```

however, it does not work with querying:

```
const rsp: QueryResult<User> = await Users.query().run();
```

this will now need to be:

```
const rsp: QueryResult<UserSchema> = await Users.query().run();
```

which is 100% fine.  Its neither here nor there, so I think you can close this issue.  Thanks!

**Comment by sebelga** [comment]
Great, thanks for the feedback!
