### ISSUE TITLE
`Model.get` returns `undefined` for querying an unknown entity when using Redis caching

### ISSUE THREAD

**Issue by Maher4Ever** [sebelga/gstore-node#119]
Hello,

I started using the Redis caching feature yesterday and my app immediately broke :( 

After looking into it I found an inconsistency in the behavior of the  `get` method of models based on whether caching is enabled or not.

Here is an example that reproduces the issue:

```es6
const redisStore = require('cache-manager-redis-store');
const Datastore = require('@google-cloud/datastore');

const gstore = require('gstore-node')({
  cache: [{ store: redisStore }]
});

gstore.connect(new Datastore);

const { Schema } = gstore;

const userSchema = new Schema({
  name: { type: String, required: true }
})

const User = gstore.model('User', userSchema);

const run = async () => {
  try {
    const user = await User.get('user')
    console.log(user)
  } catch (e) {
    console.error(e)
  }
}

run()
```

If you run this code, it will output `undefined`. However, if you disable caching, a `GstoreError` exception is thrown (which in my opinion is the thing I would expect)

**Comment by sebelga** [comment]
Hi
Thanks for reporting this. You're right, the behavior should be consistent. I will add a fix asap.
Cheers 👍

**Comment by sebelga** [comment]
Hi,
I just made a release, v4.2.6 that should fix this issue. Could you try it and let me know if it did the fix?
Also make sure that it installs with it `nsql-cache` v1.1.4 and `nsql-cache-datastore` v1.1.4.
Cheers!

**Comment by Maher4Ever** [comment]
Hello, I can confirm that the new release fixes this issue 🎊

**Comment by sebelga** [comment]
Great, thanks for the feedback!
