### ISSUE TITLE
Feature request: Ability to sanitise fields of embedded objects.

### ISSUE THREAD

**Issue by huysamen** [sebelga/gstore-node#122]
Similar to being able to index specific fields for embedded objects, it would be great if we could sanitise specific fields for embedded options, maybe along the lines of:

```
someProperty: {
  type: Object,
  required: true,
  excludeFromIndexes: true,
  read: [false, "embeddedProp1", "embeddedProp2", ...]
}
```

**Comment by sebelga** [comment]
Hi,
I like the idea, not sure about the API though. The first value would _always_ be `false` if it's an Array right?
What about

```js
someProperty: {
  type: Object,
  required: true,
  excludeFromIndexes: true,
  read: ["embeddedProp1", "embeddedProp2"] // only read those properties
}
// or
someProperty: {
  type: Object,
  required: true,
  excludeFromIndexes: true,
  excludeFromRead: ["embeddedProp1", "embeddedProp2"] // remove those properties
}
```

**Comment by huysamen** [comment]
Good point.  I prefer the 2nd approach, include by default, specify to exclude.

**Comment by sebelga** [comment]
Good. I am putting it in the pipeline... Hopefully I can work on this along with #120 soon! :smiley:
