### ISSUE TITLE
Discuss: Should an error be returned if entity is not found?

### ISSUE THREAD

**Issue by huysamen** [sebelga/gstore-node#123]
Should an error really be thrown when an entity cannot be found?  We have a lot of use-cases where it is perfectly fine when an entity cannot be found, and having to wrap all those in try-catches (we use Typescript + async/await) feels a bit unnecessary, rather than just returning `null`.

However, I realise this is a preference thing, so not too picky about it if you feel strongly about it.  My viewpoint is just that not finding an entity is not really an _error_ per-say.

**Comment by sebelga** [comment]
Hi
I understand what you're saying and yes it's just a preference. I might do it differently today :) But changing the behavior would create a breaking change I'd rather not make.

You might want to have an utility function to wrap the try/catch. Something like

```js
const fetchEntity = async (model, ...args) => {
  let res;
  try {
    res = await model.get(...args);
  } catch(e) {
    if (e.code === gstore.error.codes.ERR_ENTITY_NOT_FOUND) {
        res = null;
    } else {
        throw(e);
    }
  }
  return res;
}

// then call it anywhere

const User = require('user.model');
async function() {
    const user = await fetchEntity(User, 123);
}
```
But you'd still need to do error handling so not sure this would help really.

**Comment by huysamen** [comment]
If you want to prevent a breaking change, you could also absorb this in the library with an option?  Something like the following when constructing your `Gstore`.

```
const gs = require("gstore-node")({ errorOnEntityNotFound: false });
```

and then just having the default true?

I don't mind contributing if you are open to pull requests?

**Comment by sebelga** [comment]
Yes that would do it actually. I am opened to PR and I'd appreciate the help as I am a bit busy right now. Cheers! Also let me know about the Typescript issue in the other thread :+1:

**Comment by sebelga** [comment]
Thanks again for the PRs, I will make a release asap with those features :+1:
