### ISSUE TITLE
Embedded entities cannot store string values larger than 1500 bytes

### ISSUE THREAD

**Issue by huysamen** [sebelga/gstore-node#132]
In Datastore, indexed string values cannot exceed 1500 bytes, however unindexed values can.  When excluding an embedded entity from indexing, Datastore does exclude it and all its properties from indexing, however, you still have to explicitly pass through 'excludeFromIndexing' for the entity properties, otherwise you cannot store strings longer than 1500 bytes.

See [this](https://github.com/googleapis/google-cloud-node/issues/1916) issue.

Currently in gstore-node, you can either exclude the embedded entity, or specific properties of the embedded entity, not both.  This means if I exclude the entire embedded entity, none of its string properties can be longer than 1500 bytes.  The alternative is to exclude all its properties, which is tedious.

**Comment by sebelga** [comment]
Hello,
The excludeFromIndexes api of the Datastore is not quite very clear 😊I had an opened discussion without getting the response I wanted at the end: https://github.com/googleapis/nodejs-datastore/issues/12#issuecomment-352158700

You are saying that when setting `excludeFromIndexes: true` on an embedded entity it should **both** set it on the entity and all its properties?

**Comment by sebelga** [comment]
Ok I will give it a try as soon as I can and let you know.

**Comment by aroraenterprise** [comment]
Was there ever a fix for this? I have run into the same issue.

**Comment by sebelga** [comment]
Hi,
Sorry for the late answer. A fix will be available on the coming `v7.0.0` release.
Cheers 👍
