### ISSUE TITLE
gstore 4.3.1 build error

### ISSUE THREAD

**Issue by zeichee** [sebelga/gstore-node#137]
Since the demo project is not working for me, I tried installing the gstore-node package. 
Upon successful installation, I build my project and I'm getting many errors regarding gstore-node. 
Here are just some of the errors that I encountered upon building. 
![image](https://user-images.githubusercontent.com/10136536/49860036-ee52ef80-fe33-11e8-96e0-234bee647ada.png)

**Comment by loixlab** [comment]
Hello, could you please open the issue in the demo app repo? It would be better as it is probably not related to gstore-node.
Closing this one here, cheers!
