### ISSUE TITLE
sanitize() does not strip unknowns when using Joi schema validation

### ISSUE THREAD

**Issue by aroraenterprise** [sebelga/gstore-node#139]
Hey, I am sure I am probably doing something wrong but when I use the Joi schema to do validation, keys that are not in my schema but present in my data are not stripped in sanitize or during save. This means that basically anything present in the data is stored into the database. When i wasn't using joi for validation, sanitize/save would strip out these keys automatically. Love your help.

**Comment by sebelga** [comment]
Hi,
Thanks for reporting this, it was indeed a regression from a fix I added lately.
I just release `v4.3.3` that should fix this issue. Let me know if it's working on your side.
Cheers!
