### ISSUE TITLE
Update @google-cloud/datastore to v3

### ISSUE THREAD

**Issue by Maher4Ever** [sebelga/gstore-node#143]
Hello,

The `@google-cloud/datastore` package has a new [**v3** major release](https://github.com/googleapis/nodejs-datastore/blob/master/CHANGELOG.md#v300) which contains many bug fixes and dependency updates. It would be awesome if `gstore-node` started using this new version soon.

**Comment by sebelga** [comment]
Hi!
Thanks for the update, I will update `gstore-node` to support v3.
cheers

**Comment by alickmail** [comment]
Support!

**Comment by sebelga** [comment]
It will come with the next major release very soon. Just finishing the `populate()` feature that I think you will appreciate 😊 .
Cheers!

**Comment by sebelga** [comment]
Version `v5.0.0` has just been released. It supports @google-cloud/datastore v3 😊 
Read the doc for the breaking change on how to instantiate Gstore (it follows the same change as with the Datastore);

Closing the issue. Feel free to reopen if there is any problem.
