### ISSUE TITLE
Typescript definitions not working, uses imports from v1 of @google-cloud/datastore

### ISSUE THREAD

**Issue by mickdekkers** [sebelga/gstore-node#146]
It looks like the typescript definitions in [`/lib/index.d.ts`](https://github.com/sebelga/gstore-node/blob/master/lib/index.d.ts) are based on definitions from v1 of `@google-cloud/datastore`. v2 no longer exports certain types like [`DatastoreKey`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/dd501a1318bb8ba366cd3d3d3f93f07315f09a8b/types/google-cloud__datastore/index.d.ts#L128-L136), which causes the build to fail:

![tsc-output](https://user-images.githubusercontent.com/5085260/51908223-7fbcf780-23c9-11e9-9dc9-9ee1dca3d0fc.png)

I've created a minimum reproduction repo here:
https://github.com/mickdekkers/gstore-node-typescript-definitions-issue-repro

**Comment by sebelga** [comment]
Hi! Thanks for reporting. I am almost finishing a feature. I will look into it and fix it.
Cheers

**Comment by sebelga** [comment]
Hi @mickdekkers ,
I just released `v5.0.0` that should fix the typescript definition problem. Cou.d you upgrade and let me know if the issue persists?
Look at the documentation as there is a breaking change on how you have to instantiate Gstore on the new version.
Cheers!

**Comment by mickdekkers** [comment]
The new version fixed the issue, thank you! 😄

**Comment by sebelga** [comment]
Great, thanks for the feedback!
