### ISSUE TITLE
Convert Entity to JSON?

### ISSUE THREAD

**Issue by shaunc869** [sebelga/gstore-node#15]
Hi!

I guess this is more of a question than an issue, but is there any easy way to convert these to JSON objects that can be returned by express routes? Thank you!

**Comment by sebelga** [comment]
Hi!
If you call entity.plain() you get an object that you can pass to res.json()
If you look at a current project I am working on (https://github.com/sebelga/blog-app-googlecloud/blob/develop/controllers/comment.controller.js#L28) you see that I save the Comment and then return the saved entity in the response.
Is that what you're asking?

**Comment by sebelga** [comment]
I will close this for now, if you still have problem outputting to json you can reopen it. thanks.
