### ISSUE TITLE
how to do a UNIQUE validation

### ISSUE THREAD

**Issue by mithundas79** [sebelga/gstore-node#157]
I am using this npm with great success... but currently I could not understand how to implement **UNIQUE** validation

Currently i do it as

```nodejs
User.findOne({ phone: req.body.phone })
.then((entityData: any) => {
	res.status(200).json({ error: 'PHONEEXISTS' });
})
.catch((err: any) => {
	if (err.code) {
		if (err.code == 'ERR_ENTITY_NOT_FOUND') {
			const user = new User(saveData);
			user.save()
				.then((userData: any) => {
					const user = userData.plain();
					res.status(201).json({ user });
				})
				.catch((err: Error) => {
					self.debug(err);
					res.status(500).json({ error: err });
				});
		}
	}
})

```
But i would like to do it in my schema preferably....

**Comment by sebelga** [comment]
Hello,

You would need to add a _pre_ hook (https://sebloix.gitbook.io/gstore-node/middleware-hooks/pre-hooks) for that before saving the entity. Something like this (has not been tested)

```js

// In your schema declaration

function checkIfUserExists() {
    return this.model('User')
        .findOne({ phone: this.phone })
        .then((entity) => {
            if (entity) {
                // Already exists throw an error
                throw new Error('User already exists');
            }
        });
}


// Add the "pre" middleware to the save method
yourSchema.pre('save', checkIfUserExists);

------------------------------------------

// In some other file
const user = new user({ phone: req.body.phone });
user.save()
    .catch((err) => {
    // error should be caught here
    });
```

**Comment by yolorepo** [comment]
Thank you sir @sebelga This is exactly what I was looking for.... I think I need to spend more time on the docs really :D

**Comment by mithundas79** [comment]
Btw @sebelga few question here
1. As I have observed if ```findOne({ phone: this.phone })``` does not return entity it throw ```err``` on ```catch```.... so is ```if (entity)``` is required?

2. Say I have checks for both **email** and **phone** shall i create 2 hooks becoz in mongodb i would have used **OR** statement and wrote ```findOne({ $or: [{ phone: this.phone }, { email: this.email }] })``` how to accomplish that here.

3. As i can see the given example works fine with **Inserts** but for **Updates** I need to add to extra parameters like ```id != this.id``` or something similar.... in that case shall i create another hook, but then how to add to specifically the **update** method, is it same as in mongoose?

4. Can i add more than one hook to **save** method, so currently I have ```userSchema.pre('save', hashPassword);``` then can i add another as ```userSchema.pre('save', checkIfUserExists)```

Looking forward for your help.

**Comment by mithundas79** [comment]
Ok I got the answer for both 3 and 4 and possibly 2 as well
3.  I need to use **update hook** as ```userSchema.pre('update', checkIfUserExists)```
4. I can chain my hooks, ```userSchema.pre('save', [middleware1, middleware2])```
2. The **OR** operation I do not need if i can chain my hooks --- but still for curiosity asking is it possible to use the OR?
1. I will figure out while coding...
Thanks a lot @sebelga

**Comment by sebelga** [comment]
Hello,
Unfortunately, the Datastore does not have a "or" comparator so you need to make 2 queries (https://cloud.google.com/datastore/docs/concepts/queries#filters).

You can indeed add as many hooks as you need in an Array like you mentioned. Not sure I understook your question about update, but yes you need to add a `pre` hook on 'update'.

Hope you make it work! 😊
