### ISSUE TITLE
How to model an array of schema type - Schema.Type.Key

### ISSUE THREAD

**Issue by ejeh** [sebelga/gstore-node#159]
Please am having issues with creating an array of Schema.Type.Key.  For example, I have a particular product that customers are reviewing. Using the schema type, Schema.Type.Key, I want to populate the review property referenced in the product model with an array of reviews. How do I go about that? Thanks

**Comment by sebelga** [comment]
Hello,
Unfortunately, currently it is not possible to declare an array of references (Keys). You need to do it manually. Declare a type "Array" and save inside the Keys. You then can fetch the keys with

```js
gstore.ds.get(arrayOfKeys).then( ... )
```

**Comment by ejeh** [comment]
Please , how? show me a code example on how to go about that.

**Comment by sebelga** [comment]
As a starting point (this has not been tested!)

```js
// ./product.model.js
const productSchema = new Schema({
  reviews: { type: Array },
});

const Product = gstore.model('Product', productSchema);

// ----------------------------------

// ./reviews.model.js
const reviewsSchema = new Schema({
  description: { type: String },
});

const Review = gstore.model('Review', reviewsSchema);

// ----------------------------------

// Then, anywhere in your app

// Save a product with 2 reviews (already in the Datastore)
const reviews = [Review.key('id-1'), Review.key('id-2')];
const product = new Product({ reviews });
product.save().then( ... );

// ----------

// Function to fetch a product + its reviews
const getProduct = async (id) => {
  const product = await Product.get(id);
  const reviews = await Review.get(product.reviews);
  
  // Convert entity to JSON and replace the review Keys with entities
  return ({
    ...product.plain(),
    reviews: reviews.map(review => review.plain()),
  });
};
```

**Comment by ejeh** [comment]
Thanks for responses, I really appreciate them.

**Comment by sebelga** [comment]
You're welcome. Closing the issue as it has been resolved.
