### ISSUE TITLE
TypeScript: ref doesn't exist in ScemaPathDefinition

### ISSUE THREAD

**Issue by Balgy** [sebelga/gstore-node#165]
I 've been trying to use the library with typescript but using the 'ref' attribute in a schema definition where the type is of type Schema.Types.Key gives me a compiler error.

I checked the 'index.d.ts' file and indeed there is no ref attribute defined in the 'SchemaPathDefinition' interface. Am I doing something wrong here?

**Comment by sebelga** [comment]
Hello,
Thanks for reporting! This is indeed a bug, I will add it
Cheers
