### ISSUE TITLE
Update @google-cloud/datastore to v4

### ISSUE THREAD

**Issue by vzts** [sebelga/gstore-node#166]
First of all, thank you for this wonderful library. I really love it.

I'm persuading my team to use this library in production, but one problem is that it depends on the older datastore pacakge that might break in the long term.
It would be really nice if gstore-node supports the latest version of datastore(v4).

Meanwhile, I'd like to contribute for this update if it's not so complicated.
What would be the process? update the package and run the tests to see if it breaks?

**Comment by sebelga** [comment]
Hello,

Thanks for raising this! I am currently traveling for a few weeks so if you can contribute it would be awesome. 
Yes, update the package.json with the new version and run the tests.

If you can also run the integration tests that'd be great (I don't have them running in the CI yet). For that you need to have a local instance of Redis running on its default port. Then execute in a separate terminal `npm run local-datastore` (from the root of the repo).  
At that point you can run the tests with the "--int" flag: `npm run test -- --int`

Cheers!

**Comment by vzts** [comment]
cool I will look into it this weekend!

**Comment by vzts** [comment]
I tested with `--int` flag, and all tests has passed :)
[test_output.log](https://github.com/sebelga/gstore-node/files/3244999/test_output.log)

for future reference:
I also needed to install the datastore emulator here: https://cloud.google.com/sdk/
and run it with
`gcloud beta emulators datastore start --project=test --data-dir ~/gstore-test`
