### ISSUE TITLE
EntityKlass id not set when saving or querying entities

### ISSUE THREAD

**Issue by jacobg** [sebelga/gstore-node#172]
I have a simple unit test that saved a model I defined:
```ts
    const foo = await new models.Foo({
      bar: 1,
    }).save()
```

The returned `foo` is an instance of an `EntityKlass`. `EntityKlass` has, among many others, the following two properties:
```ts
    entityKey: entity.Key;
    id: number | string;
```

It looks like `entityKey` is set after saving, but `id` is not. Thus:
```ts
    console.log(`Saved foo entity key id ${foo.entityKey.id}`)
    console.log(`Saved foo id ${foo.id}`)
```
prints this out:
```
Saved foo entity key id 1
Saved foo id undefined
```

Also, the `entity.Key` class is defined in `@google-cloud/datastore` with the `id` property always being a string, even if it's auto-allocated as numeric. This is confusing. It seems that the `EntityKlass.id` property perhaps is intended to parse it to its intended type, but as mentioned above it's not doing that here.

The same issue also occurs when calling `model.list({ format: "ENTITY"})`.

Here's a unit test illustrating this issue:

```ts
  it('should be able to save and return the entity with key', async () => {
    const gstore = createGstore()

    type EntityType = {
      someField: string
    }
    const EntitySchema = new gstore.Schema<EntityType>({
      someField: { type: String, required: true }
    })
    const EntityModel = gstore.model<EntityType>('EntityType', EntitySchema)

    const someFieldValue = faker.random.alphaNumeric()
    const createdEntity = new EntityModel({
      someField: someFieldValue
    })
    const savedEntity = await createdEntity.save()

    // This is what a saved entity looks like
    expect(savedEntity.entityKey).to.be.instanceOf(entity.Key)
    expect(savedEntity.entityKey.id).to.be.a('string')
    expect(Number.parseInt(savedEntity.entityKey.id as string)).to.not.be.NaN
    expect(savedEntity.id).to.be.undefined // Well, this is weird!
    expect(savedEntity.someField).to.equal(someFieldValue)
    expect(savedEntity.entityData.someField).to.equal(someFieldValue)
    expect(savedEntity)
  })
```

**Comment by sebelga** [comment]
Hi,
Thanks for reporting this issue! I just opened a PR that should fix it. It will be available in the next major version. Please let me know if the issue persists 👍
