### ISSUE TITLE
Validate for "required:true"

### ISSUE THREAD

**Issue by bfellows37** [sebelga/gstore-node#18]
Seems like it should validate for "required: true" in the schema. validate.js doesn't accept nulls or zero-lengths so maybe those checks should be at the top of model.validate() and flip skip if value is null or zero-length after trimming.

**Comment by sebelga** [comment]
Hi,
Sorry I didn't understand, could you explain a bit more the issue?
thanks

**Comment by bfellows37** [comment]
This might be more of a feature request:

A way to set a schema property as required and then fail validation if null or zero-length.

Additional context:

I've built a Contact model using a schema that looks like:

    var contactSchema = new gstore.Schema({
        Email       : {
            type        : 'string',
            validate    : 'isEmail',
        },
        FirstName   : {type : 'string'},
        LastName    : {type : 'string'},
    });
    module.exports = gstore.model('Contact',contactSchema);

It's within an Express app so I require it in my controller and use it like:

    var ContactEntity = new Contact(req.body);
    // { Email: null } or
    // { Email: '' }
            
    var validate = ContactEntity.validate();
    if(!validate.success){ return res.status(400).send({code: 400, reason: "Bad Request: Data supplied is invalid"}); }

  // passes validation, doesn't send a 404

I am working around it by adding a 'default' setting to the Email property that is a single-character space, but it seems less intuitive to do it this way:

    var contactSchema = new gstore.Schema({
        Email       : {
            type        : 'string',
            validate    : 'isEmail',
            default     : ' ',
        },
        FirstName   : {type : 'string'},
        LastName    : {type : 'string'},
    });

Check out the Mongoose docs here on validation http://mongoosejs.com/docs/validation.html seems appropriate to do it like they do it

    var schema = new Schema({
      name: {
        type: String,
        required: true
      }
    });
    var Cat = db.model('Cat', schema);

**Comment by sebelga** [comment]
Oh ok I see. Yes you're right I think it would be something useful to add. I'll add it in the next release. Thanks for reporting!

**Comment by sebelga** [comment]
Just released 0.6.5 with this new feature. Tell me if it works for you. Thanks!

**Comment by sebelga** [comment]
Closing as it has been resolved. Feel free to come back for any comments.

**Comment by bfellows37** [comment]
Looks like it's working. Thanks for the update!

**Comment by sebelga** [comment]
Great, happy to hear that!
