### ISSUE TITLE
Error when using nsql cache getting multiple keys in Model.get.

### ISSUE THREAD

**Issue by aroraenterprise** [sebelga/gstore-node#187]
This happens all of a sudden when nsql cache is enabled. When i do a Model.get() for multiple ids, it will work and then all of a sudden this error comes up.

Error: Key cannot be undefined. at keyToString (~/node_modules/nsql-cache-datastore/lib/index.js:96:23)

**Comment by sebelga** [comment]
Hello,
Thanks for reporting. In order to reproduce I would need a bit more context as when this error appears. Do you know the steps that trigger that error apart from turning on the cache?

Also, could you share the full stack trace of the errors? 
Thanks!

**Comment by aroraenterprise** [comment]
Okay, I got it to reproduce. This error occurs very specifically when:
First, I have one item of let's say Attendee in the store and I use Model.get([attendeeId]) to get this entity -> everything is okay.
Now, I add another entity into the datastore and I go Model.get([attendeeId1, attendeeId2]). With cache enabled this doesn't work. Once I reset the app it starts behaving normally again. It is only when the initial call is for just one item followed by a call for more than one item.

Here is the entire trace:
`Error: Key cannot be undefined.
    at keyToString (/Users/sajarora/Projects/one_day_builds/edropin_uno/backend/node_modules/nsql-cache-datastore/lib/index.js:96:23)
    at Object._db.keyToString.key [as keyToString] (/Users/sajarora/Projects/one_day_builds/edropin_uno/backend/node_modules/nsql-cache/lib/index.js:171:61)
    at keyToString (/Users/sajarora/Projects/one_day_builds/edropin_uno/backend/node_modules/nsql-cache/lib/keys.js:17:60)
    at addToCache (/Users/sajarora/Projects/one_day_builds/edropin_uno/backend/node_modules/nsql-cache/lib/keys.js:127:30)
    at Array.forEach (<anonymous>)
    at onResult (/Users/sajarora/Projects/one_day_builds/edropin_uno/backend/node_modules/nsql-cache/lib/keys.js:131:29)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
 `

**Comment by aroraenterprise** [comment]
From further looking into it, it seems that cache.db.getEntityFromKey(entity) doesn't work when the entity is type of array which is what happens in this situation. I hope this helps you find the problem.

**Comment by aroraenterprise** [comment]
I am currently using this hack as a workaround to this issue. I disable cached when there is only one id in the array, and re-enable it when there is more than one.
`const entities = await CampaignSchema.get(
    ids,
    [],
    environment.appId,
    undefined, {
      preserveOrder: true,
      cache: ids.length === 1 ? false : true,
      dataloader: ctx.dataloader,
    });
`

**Comment by sebelga** [comment]
Hi,
Thanks for the update! I will have a look and let you know. Cheers! 👍

**Comment by aroraenterprise** [comment]
Hey, just checking for any updates on this issue. Thank you.

**Comment by sebelga** [comment]
Hi, sorry for the delay. I am very busy until next week. Hopefully, I should be able to look at this at the end of next week. Thanks!

**Comment by aroraenterprise** [comment]
That would be amazing! Thank you so much. I know you are very busy.

**Comment by sebelga** [comment]
Hi!
I've just released `v7.2.3` that should fix this bug. Thanks for reporting! Could you please test it and let me know if the issue is indeed solved?

Cheers 👍
