### ISSUE TITLE
Incompatibility with @google-cloud/datastore 0.5.0

### ISSUE THREAD

**Issue by 5un** [sebelga/gstore-node#19]
As google-cloud datastore lib has changed their entity response format from 
{ key: someKey, data: someData }
to 
{ entityData }
in @google-cloud/datastore 0.5.0 (The change is actually in this [commit](https://github.com/GoogleCloudPlatform/google-cloud-node/commit/baf0986e58a667b2cf406c07fd15171857e92afe) ), this clearly will breaks model creation. For example, trying to fetch an entity with a key would result in the following error as entity.key in the response is no longer presence.

/MyProject/node_modules/gstore-node/lib/serializers/datastore.js:23

     data.id  = entity.key.path[entity.key.path.length - 1];

                          ^
TypeError: Cannot read property 'path' of undefined

May I ask whether there is any plan to support datastore 0.5.0 soon?

**Comment by sebelga** [comment]
Hi, thanks for reporting. Yes there is plan to support it, hopefully by the end of the week.

Next thing on the list are to add Promises and follow their very nice support of it :)

**Comment by sebelga** [comment]
Hi, I just updated the library (v0.7.0) to support datastore 0.5.0. Could you upgrade and test if it works on your side. Thank you!

**Comment by 5un** [comment]
0.7.0 seems to work well so far. Thanks man. Appreciated your work and the swift update on this repo!
