### ISSUE TITLE
Error with generics Typescript definitions

### ISSUE THREAD

**Issue by carnun** [sebelga/gstore-node#194]
My current project compiles fine when I use Gstore_node 7.1.0 however when I now compile with 7.2.1 I receive a bunch of errors relating to types which are not generics. E.g.

```
import { Model } from 'gstore-node'

interface MyModelInterface {
   createdAt: Data
}

function hook(model: Model<MyModelInterface>) {
   ...
}
```

Now this code does not compile with the error:
```
Type 'Model' is not generic
```

A similar issue exists for the `Schema` type.

**Comment by carnun** [comment]
@sebelga I've created the above PR for the issue I logged. I hope it helps.

**Comment by sebelga** [comment]
Hi,
Thanks for raising the issue and opening a PR!
Could you have a look at my comments? cheers!
