### ISSUE TITLE
Exposing additional Schema and List types

### ISSUE THREAD

**Issue by carnun** [sebelga/gstore-node#196]
[This is a feature request]

I often create my own more specific interfaces on top of the schema definitions or extend methods such as the list() method. It would be great if I didn't have to redeclare `SchemaPathDefinition` and `QueryListOptions` since these are key to keeping the gstore-node interfaces intact. ( It could be that there are types already defined in gstore-node that do this, and that I have somehow missed them.)

My only other option is to allow submodule imports, but that isn't great.

Example for SchemaPathDefinition:

`export type SchemaDef<M> = { [P in keyof M]: SchemaPathDefinition }`

where M is typically some data model.

The example for `QueryListOptions` is a bit more involved since I'm creating generic schemas to save myself some boilerplate code, and I then want my code to wrap some of the interface methods from `Model` for various reasons.

**Comment by sebelga** [comment]
Hi

If I understand you well, you would like that more gstrore types be exported. Is that correct? Only the 2 you mention or is there any other?

Cheers

**Comment by carnun** [comment]
@sebelga that's correct. Additional types which would be great are:

- `EntityId`
- `EntityData`

**Comment by sebelga** [comment]
Ok! I will get back to gstore end of next week as I am quite busy this week. 👍

**Comment by sebelga** [comment]
Hi!
I've just released the `v7.2.3` version that exposes the above types. Let me know if everything is ok, cheers! 👍

**Comment by carnun** [comment]
Thanks! I'll take a look.
