### ISSUE TITLE
Model.findOne does not support options.readAll

### ISSUE THREAD

**Issue by henryYHC** [sebelga/gstore-node#197]
Contradicting what is in the documentation, the `Model.findOne` function does not support the option `findAll` based on the typing. Is it possible we can get an update on it?

**Comment by sebelga** [comment]
Hello,
Thanks for reporting, I will look into it and let you know.
Cheers 👍

**Comment by sebelga** [comment]
Hi,
I've just been testing. The `readAll` works, the only thing is that the Typescript option was indeed not present. Is that the issue you found?

**Comment by sebelga** [comment]
Hello, I just release the `v7.2.3` that should add the missing type. Thanks again for reporting, let me know if there is still an issue. 👍
