### ISSUE TITLE
Entity Key does not exist in entities returned with list()

### ISSUE THREAD

**Issue by Balgy** [sebelga/gstore-node#199]
list() returns the next page cursor and an array of entites which are of type `EntityData<>`, however the `EntityData<>` type does not include the entity's key in the data.

I need to get the keys of the entities returned with list().
Is this a bug or am I doing it wrong?

**Comment by sebelga** [comment]
Hi,

The Key is saved as a Symbol that you access from the Datastore instance (e.g. `datastoreInstance.KEY`). gstore exposes the datastore instance through `gstore.ds`.

```js
const users = await UserModel.list();

const key0 = users.entities[0][gstore.ds.KEY]; // access the key from the first item
```

As a convenience, gstore allows you to pass the `{ showKey: true }` option when calling `list()`. It will add a `__key` property to each entity data with the Key

```js
const users  = UserModel.list({ showKey: true });
```
