### ISSUE TITLE
Get() returns 404 with "12345:12345" formatted key name

### ISSUE THREAD

**Issue by micaww** [sebelga/gstore-node#2]
Similar to #1, but with getting instead. Getting an object by number ID works fine, so does a regular string name (e.g: 'testobject'). However, in my case, a string name of "12345:12345" returns 404 every time through gstore-node. Tested in gcloud works successfully.

Thank you

**Comment by micaww** [comment]
Did some looking, and the issue seems to be the behavior of `parseInt` on [model.js line 53](https://github.com/sebelga/gstore-node/blob/master/lib/model.js#L53).

According to the [Mozilla Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt), 

> If parseInt encounters a character that is not a numeral in the specified radix, it ignores it and all succeeding characters and returns the integer value parsed up to that point. parseInt truncates numbers to integer values. Leading and trailing spaces are allowed.

> If the first character cannot be converted to a number, parseInt returns NaN.

So as long as a string starts with an integer, parseInt will not pass the NaN test.

**Comment by sebelga** [comment]
Hi, thank you for your fixe. I had to also implement it for the Model.update() and Model.delete() methods so I put the logic in a separate function.
Thanks again for reporting this!
