### ISSUE TITLE
modifiedOn not automatically updating when using gstore.save

### ISSUE THREAD

**Issue by eungkyu** [sebelga/gstore-node#202]
modifiedOn is automatically updating when using entity.save, but not by using gstore.save

**Comment by sebelga** [comment]
Hi,

Thanks for reporting. Indeed it was not implemented in `gstore.save()`. I will add it. 👍

**Comment by sebelga** [comment]
I just added a fix to update the `modifiedOn` with gstore.save(). It will be available in the next release. Cheers 👍
