### ISSUE TITLE
Can't save entity with 'Date' validated property

### ISSUE THREAD

**Issue by theArina** [sebelga/gstore-node#206]
I have a model:
const schema = new Schema({
  prop: {type: Date},
});

When i try to do:
const entityData = Item.sanitize({prop: Date()});
const item = new Item(entityData);
await item.save();

It works with "Item.sanitize({prop: '2019-11-13'})" though.

**Comment by sebelga** [comment]
Hi @theArina sorry for the late answer. I will have a look and let you know. Thanks for reporting.

**Comment by sebelga** [comment]
I added a fix that will be available on the next release. For now you can use `new Date()` instead of `Date()` and it should work.
Cheers 👍
