### ISSUE TITLE
Type validation of fields with an undefined value fails

### ISSUE THREAD

**Issue by jfbenckhuijsen** [sebelga/gstore-node#21]
In model.js:824, the type of the property is validated. However, if the value of said property is equal to undefined, the property validation fails.

**Comment by sebelga** [comment]
Did you put required:true in the Schema for that property?

**Comment by sebelga** [comment]
Closing the issue, feel free to re-open it the above solution didn't work.

**Comment by jfbenckhuijsen** [comment]
Wel, the thing, is, the property isn't actually required. It's allowed from a functional perspective to be undefined.

**Comment by sebelga** [comment]
Ok I see. Would setting it as "optional: true" in the Schema be an option then? The validation would still need to be updated.

**Comment by jfbenckhuijsen** [comment]
optional: true doesn't really change anything. I'm assuming optional: true is the default. Valdation also fails in this case.

**Comment by sebelga** [comment]
Sorry didn't explain myself well. I was asking your opinion. Do you think that defining the property as "optional" would work from a functional perspective? As having a property with a value of _undefined_ or not being present at all in the data object is the same.
I will then need to update the validation to accept undefined as as valid for properties defined with optional: true. And if some value is passed it will do the validation with the "type" and "validate" setting.

**Comment by sebelga** [comment]
After giving it a thought there is no need to declare a property as _optional_ if we already have a _required_ setting. I updated the validation and **undefined** values should validate correctly on properties that are **not** defined as required.
Will be included in next release. thanks for reporting.

**Comment by sebelga** [comment]
Closing as v0.7.2 should have fixed it. Let me know if there is still an issue.
