### ISSUE TITLE
You may add support of the '!=' operator to the 'list()' query

### ISSUE THREAD

**Issue by theArina** [sebelga/gstore-node#215]

**Comment by sebelga** [comment]
Hello,

Could you please create the issue with a proper description?

thanks 👍

**Comment by theArina** [comment]
What? Rude. I just submitted feature request. You have no reason to talk to me like that.

**Comment by sebelga** [comment]
Sorry, I am not going to teach you manners when it comes to asking something to someone, especially someone that: 1. you don't know, 2. is going to work for free for you.

I let you find out on your own.
