### ISSUE TITLE
Preferred way to transform a query result back to an entity

### ISSUE THREAD

**Issue by jfbenckhuijsen** [sebelga/gstore-node#22]
As far as I can see now, results from a query are the raw results from the query executed by the underlying gcloud-node library? What would be the preferred way to convert these entities back to gstore-node Model objects?

I.e my use case is the following roughly:
``
query(..., (entities) => {
  // do something with entities, update some properties
  entity.save();
});
``

**Comment by jfbenckhuijsen** [comment]
Ok, been experimenting a bit. So far I've come up with this:

`return entities.map((entity) => {
            delete entity.id;
            return new MyModelClass(entity, entity[gstore.KEY]);
        });`

The delete entity.id seems needed as the query result includes this value, whereas the schema doesn't define this as a valid property. I am seeing some weird behaviour though, where saving the returned entity seems to result in new entities being added, instead of the existing one being updated.

**Comment by sebelga** [comment]
That might be something nice to add as an option parameter to query.
Until then you guessed right that you need to delete the id first. Then, try something like this in your map (untested):
```
return entities.map((entity) => {
    delete entity.id;
    return MyModelClass.__model(entity, null, null, null, entity[gstore.KEY]);
});
```
Tell me if it worked.

**Comment by jfbenckhuijsen** [comment]
Doesn't seem to give the desired effect. When debugging, in model.js:717, var entity is constructed. In the first case (i.e. after construction of the initial object), this.entityKey contains four fields:

- kind: User
- namespace: undefined
- path: undefined
- name : "[some uuid generated string]"

After executing a query, I call save again on the object constructed in the way described above. When I reenter model.js:717, this.entityKey does not have the name property.

**Comment by jfbenckhuijsen** [comment]
Been debugging this on the fork I created, have the feeling the fromDatastore() function in datastore.js somehow does not copy the key.

**Comment by sebelga** [comment]
Sorry I made a mistake. Inside the map function, its `gstore.ds.KEY` to access the Symbol for the entityKey. So try with:
```
return entities.map((entity) => {
    delete entity.id;
    return MyModelClass.__model(entity, null, null, null, entity[gstore.ds.KEY]);
});
```
It should work.

**Comment by sebelga** [comment]
Did you have a chance to try the solution?

**Comment by jfbenckhuijsen** [comment]
Yes. It worked. After I finished with the virtual properties pull request, I'll craft up a feature to have this in the library itself. 

Verstuurd vanaf mijn iPhone
