### ISSUE TITLE
Add support for typing virtual proprties

### ISSUE THREAD

**Issue by Maher4Ever** [sebelga/gstore-node#220]
Hello,

I've found yet another small missing feature when trying to type my code that uses `gstore-node` :)

Consider the following code

```typescript
import { Gstore } from 'gstore-node'

const gstore = new Gstore()

const { Schema } = gstore

interface UserType {
  firstName: string;
  lastName: string;
}

const schema = new Schema<UserType>({
  firstName: { type: String },
  lastName: { type: String }
})

schema.virtual('fullName').get(function (this: UserType): string {
  return this.firstName + ' ' + this.lastName
})

const User = gstore.model('User', schema)

const user = new User({ firstName: 'Some', lastName: 'One' })
console.log(user.fullName.toLowerCase()) // Error: Property 'toLowerCase' does not exist on type 'CustomEntityFunction<UserType>'.ts(2339)
```

As you can see, all virtual properties have `CustomEntityFunction<T>` as their type instead of the return type of the `get` function. One solution I found was to add the `fullName` property to the interface as an optional property. 

However, it would be much better to deduce the return type of the `get` function and use that for the virtual properties (it should be possible with [`ReturnType<T>`](https://www.typescriptlang.org/docs/handbook/utility-types.html#returntypet)).

**Comment by Maher4Ever** [comment]
Digging through the code I found another [`Entity`](https://github.com/sebelga/gstore-node/blob/master/src/entity.ts#L563) type (close to this [`Entity`](https://github.com/sebelga/gstore-node/blob/master/src/index.ts#L301) type but has 2 genetic parameters). The second parameter to this other `Entity` type is also accepted by the `Schema` type. 

The fact that both `Entity` and `Schema` accept this second parameter allowed me to elegantly fix the compilation error:

```typescript
interface UserType {
  firstName: string;
  lastName: string;
}

interface UserVirtuals {
  fullName: string;
}

const schema = new Schema<UserType, UserVirtuals>({
  firstName: { type: String },
  lastName: { type: String }
})

// [...]

console.log(user.fullName.toLowerCase()) // OK
```

However, I'd like to confirm this is the correct way to handle this and that I'm not using an internal generic variable. @sebelga Can you please confirm this?

**Comment by sebelga** [comment]
Hi @Maher4Ever, sorry for the very late answer!

Yes using the second generic type seems to do the trick. To be honest, the generic type if `M` was for "methods" 😊, but it can also be used for virtual properties. Thanks to your PR https://github.com/sebelga/gstore-node/pull/221 it correctly casts the additional prop.

I will close the issue as it is resolved, cheers!
