### ISSUE TITLE
Support for @google-cloud/datastore version 5

### ISSUE THREAD

**Issue by jacobg** [sebelga/gstore-node#227]
As of 2020-04-17, version 5.1.0 is now available:
https://www.npmjs.com/package/@google-cloud/datastore

**Comment by sebelga** [comment]
Hi @jacobg 

I just released `v7.2.5` that supports v5 of google-cloud datastore.

Let me know if there is any issue. Cheers! 👍

**Comment by jacobg** [comment]
Thanks so much @sebelga! I hope to try it soon and let you know. Be well!
