### ISSUE TITLE
How to validate a value agains another property?

### ISSUE THREAD

**Issue by oander11** [sebelga/gstore-node#238]
Hi,
it's not clear to me how to write a custom validation function which validates two properties in relation to each other. The code below doesn't work since `paymentType` is undefined in the scope of the validator function. Is there a way to do this?
```
const paymentSchema = new Schema({
    paymentType: {type: String, required: true, validate: 'isUppercase'}, // CARD | SWISH
    currency: {type: String, default: 'SEK', validate: {rule: validateCurrency, args: [paymentType]}}
});

function validateCurrency(currency, validator, paymentType) {
    if (!validator.isUppercase(currency)) return false;
    // payment with SWISH only supported for currency 'SEK'
    if (paymentType === 'SWISH' && currency !== 'SEK') return false; 
    return true;
}
```

**Comment by sebelga** [comment]
Hi,

Unfortunately, this is not possible to do inside the validation. I would suggest adding a "pre" hook before saving and refect the Promise if your condition fails.

Here is the doc: https://sebloix.gitbook.io/gstore-node/middleware-hooks/pre-hooks

Cheers
