### ISSUE TITLE
UnhandledPromiseRejectionWarning on model.get() when a key doesn't exist

### ISSUE THREAD

**Issue by raynux** [sebelga/gstore-node#26]
When giving a non-existent key to `model.get()`, I get

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'Symbol(KEY)' of undefined
```

and I cannot `catch` the rejection of Promise, like

```javascript
User.get('NON-EXISTENT-KEY')
.then((entities) => {
  // an entity found
})
.catch((err) => {
  // never happen
})
```

I am using `gstore-node 0.8.0`, `google-cloud 0.44.2` and `node v6.9.1`. I guess something happening here?
https://github.com/sebelga/gstore-node/blob/master/lib/model.js#L110

**Comment by sebelga** [comment]
Hi,
Yes it seems to be a bug. Could you try to replace line 116 with:
`if (data.length === 0 || typeof data[0] === 'undefined') {`
to see if it solves.

I will have a look into it anyway too.
Thanks for reporting!

**Comment by raynux** [comment]
Thanks @sebelga. It works! Send the one-line fix PR.
