### ISSUE TITLE
Add Transaction support to `findOne` option

### ISSUE THREAD

**Issue by dmk1111** [sebelga/gstore-node#260]
## Related Issues

* Add any related issues here

## Motivation

In order to have consistency across the application & reduce amount of requests to Datastore, it would be great if we have possibility to pass Transaction to `findOne` method as well.

## Proposed solution

#259 feat(query): add transaction parameter to `findOne`

**Comment by dmk1111** [comment]
@carnun @sebelga guys, could you please check this one?

**Comment by carnun** [comment]
@dmk1111 at the moment we only support transactions on methods which do not internally use the Datastore queries, i.e. it is supported on `get`, `update`, `query`, `delete` and `save`; but not on `list`, `findOne` and `findAround`. I typically use `query` directly if I want to use transactions in the later cases, in this way I am aware of exactly what is involved in my transaction. E.g.

```
const findIds = async (keyValues, transaction) => {
   const query = store.query(transaction)
    Object.keys(keyValues).forEach((key) => {
      query.filter(key, keyValues[key])
    })
    const results = await query.select('__key__').run()
    return results?.entities.map({ id } => id)
}
```

You can probably adapt the above to write your own helper method to have a findOne with transactions.
