### ISSUE TITLE
Support filtering for a missing optional property.

### ISSUE THREAD

**Issue by jessupjn** [sebelga/gstore-node#261]
Example:
```
const nft = new Nft({
    ...
    owner: { optional: true }
});
```
I want to query for all `Nft` entities that aren't owned (have no `owner`). Proposal would be to filter to `undefined` or similar.
```
const nfts = await Nft.list({
  filters: [[`owner`, undefined]],
});
```

**Comment by carnun** [comment]
@jessupjn Google Datastore does not support queries for fields which have non-existent values and so we can't implement this reliably in the gstore_node library itself. Please take a look at the GQL documentation about `null` queries here - https://cloud.google.com/datastore/docs/reference/gql_reference#tips_about_gql_behavior.
