### ISSUE TITLE
Promise version of Model.findOne returns an array

### ISSUE THREAD

**Issue by raynux** [sebelga/gstore-node#36]
Isn't this inconsistent?

```javascript
Model.findOne({foo: 'bar'}, (err, entity) => {
  // entity != Array
})
```

versus

```javascript
Model.findOne({foo: 'bar'}).then((entities) => {
  // entites == Array
})
```

**Comment by sebelga** [comment]
This is the way it works to support both callback and promise.
As the callback can be called with several properties: `cb(null, true, 123)`, the Promise transform of it is an Array `Promise.resolve([true, 123])`.  
If it happens to only have 1 argument it is still an Array with one item.

**Comment by raynux** [comment]
@sebelga Ah, makes sense. Thanks!
