### ISSUE TITLE
Issue when calling Model.get with an array with a length of 1

### ISSUE THREAD

**Issue by sawyerh** [sebelga/gstore-node#37]
If you call the `Model.get` method with an array consisting of only one ID, nothing seems to be returned.

For example, calling the following returns an array of 2 entities:

```js
MyModel.get([10, 15])
```

However calling the following doesn't return anything:

```js
MyModel.get([10])
```

**Comment by sebelga** [comment]
Hi, thank you for reporting, I spotted the error :) I will bring a fix asap.

**Comment by sebelga** [comment]
Hi,
Sorry this go caught long time in PR without merging. :) It should be solved in the latest v0.10.0 release.
thanks again for reporting.
