### ISSUE TITLE
Only allows simple validation rules

### ISSUE THREAD

**Issue by mAiNiNfEcTiOn** [sebelga/gstore-node#38]
Hi @sebelga,

First, thanks for this beautiful project. Eases the implementation by 400%. You're awesome, keep up the good work (and have a Happy New Year 🎉).

# What's the issue:
I read that you use the `validator.js` - we can even see it in action in [this line](https://github.com/sebelga/gstore-node/blob/master/lib/model.js#L977)  - but that implementation only supports simple validation rules that don't expect additional parameters (e.g. the [isIn](https://github.com/chriso/validator.js#validators) rule).

# How could it be solved:
I suggest either to pass something extra on the object like:

```js
{
  validate: 'isIn',
  validation_args: [ /* an array of multiple args */ ],
  // ...
}
```

or change the `validate` prop to support both string, object/array:

```js
// simple case
{
  validate: 'isEmail'
}

// complex case
{
  validate: {
    rule: 'isIn',
    args: [ /* ... */ ]
}

// another approach
{
  validate: ['isIn', arg2, arg3, arg4, ..., argN]
}
```

Or just say, "No we only support simple cases" :)

**Comment by mAiNiNfEcTiOn** [comment]
Well, the _isIn_ example is not the best (just checked the `values` prop to validate that, but think for example on the _isIP_ or _isLength_, etc...

**Comment by sebelga** [comment]
Hi, thanks for the very kind words! Happy new year to you too... I totally agree with this proposition, I had on my todo list something very similar but never put the time to implement it. Now I have good reason to work on it :) I like your second option, being able to pass an object with an array of arguments. I will try to find some time soon to add this feature as this beginning of the year if very busy for me. Thanks again!

**Comment by mAiNiNfEcTiOn** [comment]
@sebelga my pleasure 👍  would you mind if I implement it and issue a PR or do you prefer to do it yourself?

**Comment by sebelga** [comment]
@mAiNiNfEcTiOn great if you can work on this, go ahead. Please don't forget to add the coverage for it. many thanks! :)

**Comment by mAiNiNfEcTiOn** [comment]
@sebelga sure, will try at least. Just to confirm, you'd prefer this one:

```js
{
  validate: {
    rule: 'isIn',
    args: [ /* ... */ ]
}
```

right?

**Comment by sebelga** [comment]
Yes I would prefer that one to avoid to add a new parameter. thanks!
