### ISSUE TITLE
Does this project support validation of `embedded entity`

### ISSUE THREAD

**Issue by jainanshul** [sebelga/gstore-node#41]
For an entity like below?

```
id: string
results: {
  "success_rate": 90.0,
  "failure_rate": 50.5
}
```

**Comment by sebelga** [comment]
Hi, no it does not but it would be a good feature to add. I put it on my todo list :)

**Comment by mAiNiNfEcTiOn** [comment]
Actually this brings the opportunity to consider custom validation functions :)

Doing something like:

```js
// Private function, receives the value to be validated. Other args defined in the Schema.
const myCustomFunction = (value, arg1, arg2, arg3, arg4, ..., argN) => {
  const isValid = ['success_rate', 'failure_rate'].every(key => (key in value) && (typeof value[key] === 'number'));
  return isValid;
};

// Model/Schema definition
const Model = gstore.model('MyModel', {
  results: {
    type: 'object',
    validate: myCustomFunction
    args: ['arg1', 'arg2', 'arg3', 'arg4', ..., 'argN']
  }
});
```

(Just my 2 cent)

**Comment by sebelga** [comment]
@mAiNiNfEcTiOn I think that's a great idea. If you want to give it a try go ahead. I am right now in the middle of changing both job + city so I won't have much time these coming weeks to work on gstore. All the help very much appreciated! :)

**Comment by mAiNiNfEcTiOn** [comment]
@sebelga ok, will dedicate some time to it tomorrow. 👍 

Success for your new adventure!

**Comment by sebelga** [comment]
thanks @mAiNiNfEcTiOn !

**Comment by mAiNiNfEcTiOn** [comment]
Hi @jainanshul and @sebelga , sorry for _no input_ on this one. Got hit by a storm of stuff to do at work.

Will try to find some time during the next week to do this implementation.

**Comment by jainanshul** [comment]
No rush, thanks for the quick update.

**Comment by sebelga** [comment]
Hi @mAiNiNfEcTiOn No problem, I understand perfectly I am in the same situation! :) Hopefully in a week or so I should be able to work again on gstore-node

**Comment by sebelga** [comment]
@mAiNiNfEcTiOn after some time working on the refactor of all the responses in the library I am back on looking at new feature :)  Probably the custom function validation would be the next one. I guess that you are still quiet busy, should I have a look at it based on your suggestion?

**Comment by machinshin** [comment]
hi @sebelga, 

I would also love to have this embedded validation feature.

**Comment by mAiNiNfEcTiOn** [comment]
@machinshin and @sebelga sorry about that... Became a father on the 11th of April 2017 🎉 and before didn't have much time (neither now ... but at least I came up with this PR to try to implement it)

**Comment by sympresa** [comment]
@mAiNiNfEcTiOn no problem, congrats for your new child! And thanks for the PR. I made some comment there,

**Comment by sebelga** [comment]
@mAiNiNfEcTiOn no problem, congrats for your new child! And thanks for the PR. I made some comment there, I will now run the tests

**Comment by sebelga** [comment]
@jainanshul @machinshin it has just been released in the last version. Thanks again to @mAiNiNfEcTiOn for the feature 👍

**Comment by jainanshul** [comment]
Thank you both for working on it. Will test and provide feedback shortly.

**Comment by machinshin** [comment]
@mAiNiNfEcTiOn congratulations to you & your partner on your new baby! :) 
Totally understand that fatherhood has to take priority, and thanks for getting back to this PR! :) 

@sebelga awesome, thank you!
