### ISSUE TITLE
Does the global save aka batch save operation support transactions?

### ISSUE THREAD

**Issue by jainanshul** [sebelga/gstore-node#43]
From the code it looks like the global save https://github.com/sebelga/gstore-node/blob/master/lib/index.js#L100 is a wrapper around google-cloud/datastore's save method and doesn't use transactions.

**Comment by sebelga** [comment]
Hi! Sorry for the very late answer. I am in the middle of a big change professionally and haven't been able to work on any personal work.  For now gstore does not support transaction for the global save but I will have a look into it because it would be a nice feature to add. Thanks for the feedback!

**Comment by sebelga** [comment]
Hi,
I just published v0.10.0 with support for transaction. Could you confirm it is working on your side? Feel free to reopen the ticket. Thanks again for the suggestion.

**Comment by jainanshul** [comment]
Sure I will as soon as time permits.

**Comment by lostpebble** [comment]
I've been trying this out tonight, and it seems that when I pass an array of entities, it only saves the last one.

Also, I can't pass an array of gstore-node Entities - I have to make the array contain only the `entityData` of each Entity for it to work. Would be nice to have a solution for saving arrays of Entities, each one being created through the base method of `new Model({ data }, id)`.

**Comment by sebelga** [comment]
Hello,
Thanks for reporting. It might be a bug. Could you replace in lib/index.js the line 114

```
// before
return transaction.save(entities);

// change to
return transaction.save(args[0]);
```

to see if it solves the problem.
thanks!
