### ISSUE TITLE
Is there any way to save data using insert and not upsert?

### ISSUE THREAD

**Issue by digaresc** [sebelga/gstore-node#44]
Hello!

Does all the "save" operations works as upsert(which will overwrite an entity if it already exists in Cloud Datastore)  or is there any way to use insert(which requires that the entity key not already exist in Cloud Datastore)?

Thanks in advance.

**Comment by digaresc** [comment]
My mistake,  I wasn't validating the error from the save option.

**Comment by sebelga** [comment]
Hi, yes indeed for now the "save" method correspond to the gcloud "save" (https://googlecloudplatform.github.io/google-cloud-node/#/docs/datastore/0.6.0/datastore?method=save). It would be a nice feature to be able to "insert" requiring that the key provided does not exist. I guess that's what the  _method_ parameter does in glcoud.

**Comment by sebelga** [comment]
Hello,
I just release v0.10.0 and I added the possibility to pass a method when saving. Could you confirm it works on your side? And feel free to re-open the ticket if it does not, thanks for the suggestion!
