### ISSUE TITLE
`deleteAll` can not delete more than 500 entities at at time

### ISSUE THREAD

**Issue by jainanshul** [sebelga/gstore-node#45]
I get an error below when deleting a table with more than 500 entities. This is because the `deleteAll` function seems to be fetching the entries first and then trying to delete them in one go instead of breaking them down to a batch of 500. Workaround is do the same by the caller but that makes `deleteAll` function unnecessary.

`cannot write more than 500 entities in a single call`

**Comment by sebelga** [comment]
Hi, thanks for reporting. I didn't know of this limitation so I will implement it inside the deleteAll. I have been really busy lately but I should find some time this wk.... :)
