### ISSUE TITLE
Question: Is there an example on how to do referenceProperty?

### ISSUE THREAD

**Issue by ashwinputhige** [sebelga/gstore-node#52]
I am new to both `datastore` and `gstore-node`. Having a hard time figuring out how to write the `schema` for `one-to-many` and `many-to-many` relationships without using hierarchal relationships.

If we take a small example of a `User` having many `Address`es, how should the schema look ?
```
const userSchema = new Schema({
    name: { type: 'string' }
});
```
```
const addressSchema = new Schema({
    city: { type: 'string' }
});
```

I apologize for posting a question here.

**Comment by cristyansv** [comment]
Because this is not an SQL database, you can model the data as best match your use case.
Basically there are no exact rules or patterns.

For example you could use an array of address ids.

Usually a type of data not as complex as an address, would simply be embedded in the same model.

For more complex solutions you can use something like


```javascript
const userSchema = new Schema({
    name: { type: 'string' },
    addresses: {type: 'object }
});
}
```
where:

```javascript
addresses = {
    'addreessId':{
         location: 'home'
     }
}
}
```

**Comment by ashwinputhige** [comment]
Thank you for the quick response. Looks like I have to understand the basics of `datastore` a little bit more.

**Comment by sebelga** [comment]
Hello, don't worry it takes some time to fully grasps. :)  
Look also at the relationship between Ancestors > Entity. You can create vertical relationship that way. For example a BlogPost entity could by the ancestor of Comment Entity. Then you could retrieve all the comments for a BlogPost with a query searching for all the comments having as ancestor: ['BlogPost', 123].

**Comment by cristyansv** [comment]
@sebelga Can you make an code example about ancestors? I'm also a bit confused by this.

**Comment by sebelga** [comment]
Here a small example with a BlogPost entity and a Comment entity.
I didn't include the error handling for demo purpose.

```
// blogpost.model.js

const gstore = require('gstore-node');
const Schema = gstore.Schema;

const schema = new Schema({
    title: { type: 'string' }
});

// 'BlogPost' will be your entity kind in the Datastore
module.exports = gstore.model('BlogPost', blogPostSchema);
```
----------

```
// comment.model.js

const gstore = require('gstore-node');
const Schema = gstore.Schema;

const schema = new Schema({
    title: { type: 'string' },
    text: { type: 'string', excludeFromIndexes: true } // you can't index big text
});

module.exports = gstore.model('Comment', blogPostSchema);
```
----------

```
// comment.controller.js

const gstore = require('gstore-node');
const Comment = require('./comment.model');

/*
 * Controller for an Express route with the bodyParser middleware
 * Will create a new comment with an Ancestor (a BlogPost)
 */
function postComment(req, res) {
    const data = req.body;  // { blogId: 123, comment: { title: 'hi', text: 'something' } }
    const blogId = data.blogId;
    const commentData = Comment.sanitize(data.comment); // always sanitize
    const comment = new Comment(commentData, null, ['BlogPost', blogId]);  // create entity with ancestor

    comment.save().then((response) => {
        const entity = response[0];
        res.json(entity.plain());
    });
}
```
----------

```
// blogpost.controller.js

const gstore = require('gstore-node');
const BlogPost = require('./blogpost.model');
const Comment = require('./comment.model');

/*
 * Controller for an Express route
 * Will retrieve a blogPost with its comments
 */
function getBlogPosts(req, res) {
    const blogPostId = req.query.id; // queryParams ?id=123

    BlogPost.get(blogPostId).then((response) => {
        const blogPost = response[0].plain();
        
        // get all comments
        const query = Comment.query().hasAncestor(gstore.ds.key(['BlogPost', blogPost.id]));
        query.run().then((response) => {
            const entities = response[0];
            
            // We add the comments to the blogPost
            blogPost.comments = entities;
           
            // return the blogPost + comments
            res.json(blogPost);
        });
    });
}
```

**Comment by cristyansv** [comment]
@sebelga Excellent example, thanks!

**Comment by sebelga** [comment]
Thanks. Yes you're right this might help others if it was in the doc. I am in the middle of passing all the docs to gitbook, I will put this example there.

**Comment by ejeh** [comment]
Pls how can I retrieve or count matching documents from datastore collection using gstore-node module like the count method used in moogodb @sebelga . Thanks in advance genius.
