### ISSUE TITLE
update() throwing errors

### ISSUE THREAD

**Issue by ox** [sebelga/gstore-node#54]
I have been investigating a failing test in our test suite and am struggling with a test that basically validates some params and calls `Model.update()`. The call to `Model.update()` ends up throwing an unhandled rejection:

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '0' of undefined
```

After some debugging I found the error being thrown at [`model.js:258 (onEntityUpdated)`](https://github.com/sebelga/gstore-node/blob/77672ae5eccd06435df5be156fdbf4a2ac136edf/lib/model.js#L258), where `updateData` is `undefined`. This sort of makes sense as `model.save()` doesn't return the created entity, but this seems like a common use case and I figured the tests would cover a case like this.

I made a bare test that has this issue. DevApp has just 2 fields: `appName: string`, `type: number`:

```js
const newName = 'New Test App Name';
const fApp = new DevApp({appName: 'f-app', type: 0});

return fApp.save(function (err) {
  assert.ifError(err);
  assert.equal(fApp.appName, 'f-app');
  return DevApp.update(fApp.entityKey.id, {appName: newName})
    .then((retApp) => {
      assert.equal(retApp.appname, newName);
      done();
    });
```

This is a bit contrived as I couldn't get a sane, promise-only version working either:

```js
return fApp.save()
  .then(() => {
    return DevApp.update(fApp.entityKey.id, {appName: newName});
  })
  .then((retApp) => {
    assert.equal(retApp.appname, newName);
    done();
  })
  .catch(console.error);
```

This errors with: `{ code: 400, metadata: Metadata { _internal_repr: {} } }`

I would like to be able to save a model, update it, and see the changes updated (all in a promise chain). 

Am I doing something unreasonable or wrong? Any help would be appreciated.

**Comment by micaww** [comment]
Hey @ox,

I've recreated and altered your code slightly like so:

```javascript
const gstore    = require('gstore-node');
const assert    = require('assert');

gstore.connect(require('@google-cloud/datastore')());

const DevApp = gstore.model('DevApp', new gstore.Schema({
    appName: {
        type: 'string'
    },
    type: {
        type: 'number'
    }
}));

const newName = 'New Test App Name';
const fApp = new DevApp({appName: 'f-app', type: 0});
fApp.save()
    .then(() => {
        return DevApp.update(fApp.entityKey.id, {appName: newName});
    })
    .then((retApp) => {
        const [updatedApp] = retApp;
        assert.equal(updatedApp.get('appName'), newName);
    })
    .catch(console.error);
```

It works! There's a couple of things different here.

First, any part of the Gstore API that retrieves an entity through a Promise, such as `Model.get()` or `Model.update()`, will actually return an array. So in my code on the second `.then()` clause, `retApp` is an array, and `updatedApp` (the Entity you're looking for) is the first item in that array.

Second, Entity properties cannot be accessed directly from its Gstore instance. Instead, to access properties of an Entity object, use the `Entity.get(String property)` method on that instance. It'll return a variable in the type that your Schema states.

**Comment by ox** [comment]
Ahh, thank you @micaww! You are indeed correct about multiple items being returned for updates and that example working. I managed to trace the error down to a require of `@google/cloud-trace` in one of our test dependencies. Not sure how it factors into this but glad to have figured that out. Thank you!
