### ISSUE TITLE
pre-hooks: how does __override work

### ISSUE THREAD

**Issue by machinshin** [sebelga/gstore-node#60]
I'm reading the gstore-node docs & I'm not clear on how the __override property on discussed here `https://sebelga.gitbooks.io/gstore-node/content/middleware-hooks/pre-hooks.html` works (and what is it for)?

can you elaborate & give an example?

**Comment by sebelga** [comment]
Yes indeed I see that the docs are not very explicit :)

If you originally call this for example:

```js
UserModel.delete(123, ['Dad', 'parentId']).then( ... )
```
You can override the 2 parameters passing an Array with the new arguments inside an object with __override property.

```
userSchema.pre('delete', function pre() {
   // ... whatever
   return Promise.resolve({__override: [456, ['Dad', 'anotherId']]});
});
```

Hope it is clearer like this, I will put that in the docs.

**Comment by machinshin** [comment]
unfortunately no, that isn't clearer. What is the usecase for this `__override` functionality?

**Comment by sebelga** [comment]
The functionality is there in case it might be useful to some. Like a proxy, each time an entity is deleted a async business rule could be fired and change/add the Ancestors it belongs or change the namespace.  I admit there might not be many use cases but it's there in case it might be useful.
