### ISSUE TITLE
Cannot read property 'key' of undefined when trying to add to Datastore

### ISSUE THREAD

**Issue by DaveyEdwards** [sebelga/gstore-node#61]
First off sweet project cant wait to get it working!

I am trying to get the minimal setup working and when I run my seed function to add a page to Datastore I get: cannot read property 'key' of undefined.  

I have tried every different variation I could from going through the docs, and not sure if there a way I can define the key on a field in the model.

My create function
**_Note_** 
- that I am passing a object directly to it so i changed req.body to req.
- The id I want to use is _id field on my model(I have this working without the use of gstore-node).  I also chose to use _id because I would have naming conflict with my frontend relay/graphql
- Console.log does output the correct _id string of entityData._id

```
/* eslint no-unused-vars: 0 */
const gstore = require('gstore-node');
const Page = require('../../../models/datastore/pageSchema');

const createPage = (req, res, next) => {
  const entityData = Page.sanitize(req);
  const page = new Page(entityData, entityData._id);

  page.save()
    .then(entity => res.json(entity.plain()))
    .catch(err => next(err));
};
```

And the full error:
```
H:\Coding\Projects\react-starter-kit\node_modules\gstore-node\lib\entity.js:158
    return namespace ? self.gstore.ds.key({ namespace, path }) : self.gstore.ds.key(path);
                                                                               ^

TypeError: Cannot read property 'key' of undefined
    at createKey (H:\Coding\Projects\react-starter-kit\node_modules\gstore-node\lib\entity.js:158:80)
    at ModelInstance.Entity (H:\Coding\Projects\react-starter-kit\node_modules\gstore-node\lib\entity.js:25:30)
    at Model (H:\Coding\Projects\react-starter-kit\node_modules\gstore-node\lib\model.js:21:1)
    at ModelInstance (H:\Coding\Projects\react-starter-kit\node_modules\gstore-node\lib\model.js:23:31)
    at createPage (H:/Coding/Projects/react-starter-kit/src/data/queries/googleDatastore/page/controller.js:23:19)
    at Object.<anonymous> (H:/Coding/Projects/react-starter-kit/src/data/seed/index.js:20:1)
    at Module._compile (module.js:570:32)
    at loader (H:\Coding\Projects\react-starter-kit\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (H:\Coding\Projects\react-starter-kit\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
error Command failed with exit code 1.
```

My model
```
const gstore = require('gstore-node');

const Schema = gstore.Schema;

const pageSchema = new Schema({
  _id: {
    type: 'string',
    required: true
  },
  path: {
    type: 'string',
    optional: true
  },
  public: {
    type: 'boolean',
    required: true,
    default: false,
    excludeFromIndexes: true
  },
  ... rest of fields
});

const listSettings = {
  limit: 25,
  order: { property: '_id' },
};

pageSchema.queries('list', listSettings);

module.exports = gstore.model('Page', pageSchema);

```

**Comment by DaveyEdwards** [comment]
So I found 2 problems that I had:

1. I had to add the following inside my controller.js file with the rest of my database calls instead of having it in the server.js like mentioned in the setup (I am guessing their is a way to have it only in the serverjs?
```
const datastore = require('@google-cloud/datastore')({
  projectId: 'myiworlds-164603',
  keyFilename: './src/google_api_service_key.json'
});
```
2. I had a field of type object and was trying to pass a string.  For some reason none of my error handeling works and always complains "UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: next is not a function".  Going to try and fix this

**Comment by sebelga** [comment]
Hello,
Thanks for the kind words :)
Yes, for the first error that you have it is related with the connection to the \"google-cloud/datastore"
You should only import it once in your server.js file, **not** in your controller. If you have the "Cannot read property 'key' of undefined" error it means that you are probably requiring the controller file before you configure and connect. (for example if you require your routes before you do the following:

```
// server.js
const datastore = require('@google-cloud/datastore')({
  projectId: 'myiworlds-161403',
  keyFilename: './src/google_api_service_key.json'
});

// Connect gstore to the datastore
gstore.connect(datastore);
```

About your second error it seems that the method is not part of a middleware (the "next" function is undefined). From where is the method called?

**Comment by DaveyEdwards** [comment]
So I keep my server going and when I was trying to add things to the datastore it was from a seed file that gets called in another console tab. I was thinking that if my server is running it should be able to see it. When I looked back at my project before using gstore-node I realized I had my datastore connection in my controller equivalent to,   

Seed file that is run on command
```
import { generatePages } from './pages';
generatePages();
```

inside /pages
```
import { createPage } from '../queries/googleDatastore/page/controller';

export async function generatePages() {
  pages.map((page) => {
    createPage(page);
    console.log('\n', '__PAGE__',  '\n',  page );
  })
}

const pages = [
  {
    _id: 'project00001000000000000000000000001',
    path: 'examples/project/default',
    public: true,
    type: 'project',
    rest of object fields/pages
```
Inside  controller file.  I had to change up how the function was written to get rid of the next function undefined problem.
```
export async function createPage(page) {
  let response = null;

  try {
    const entityData = Page.sanitize(page);
    const pageEntity = new Page(entityData, entityData._id);

    response = await pageEntity.save();

  } catch (err) {
    console.info('savePage err', err)
  }
  return response;
}
```

If its helpful for the gitbook I could give you my other functions written like that for others to see

**Comment by sebelga** [comment]
So are you saying that you solved your problem? :Can't figure out if you're posting a bug or a solution :)
I don't understand when you say "it was from a seed file that gets called in another console tab.", do you mean 2 separate node servers?

**Comment by DaveyEdwards** [comment]
Sorry for the confusion, it should almost be its own issue.  In regards to the server.js file having the connection I can't get that to work (not that big of a deal).  

I have 1 console open where my app is running and then I open another console to run the seed command which does not go through the server.js (i think is the cause of the problem).  It just runs a command which interacts with the controller file to add items to the database.

The end part was a solution to my next is not a function problem ;) 

ps. If I want to buy you a few coffees for helping should I send a message on your website requesting your paypal email?

**Comment by sebelga** [comment]
Yes in Node if you execute another script in another console it's a different process that is isolated from each other (so yes in that case you need to import and configure the google/datastore + gstore twice, one in each process).

I am finishing a little demo app to show how to use gstore with the connection, model definition and controllers. I hope to finish it in the next 2 weeks..... :)

Thanks for the coffee but I am very grateful for everything I get from the Open source community so gstore is my way to give something back. Cheers!!
