### ISSUE TITLE
Request: Add example to documentation for querying based on a array of ids

### ISSUE THREAD

**Issue by DaveyEdwards** [sebelga/gstore-node#62]
It had taken me while to figure out how to get it working and was thinking a example with returning objects they can use would be very helpful to new comers.  In the Gitbook it is on the models/methods/GET documentation, but I think that adding a example to map out the entities and use plain() would be a very common requirement for people.  It would also be good to add it to the readme where the other function calls are. Me a year ago probably would have never figured it out :)

**My function for fetching based on a array of _id's and returning objects**
_If there is a more performant way to do this please let me know!_
```
export async function getPagesBy_id(_ids) {
  let response = null;

  try {
    response = await Page.get(_ids, null, null, null, { preserveOrder: true })
      .then((entities) => {
        return entities.map((entity)=> {
          return entity.plain();
        });
    });

  } catch (err) {
    console.log('getPagesBy_id err', err);
  }

  return response;
};
```

**Comment by sebelga** [comment]
Thanks for the advice, I will add an example for a list of ids.
I would refactor your example like this

```js
export async function getPagesBy_id(_ids) {
  try {
    const response = await Page.get(_ids, null, null, null, { preserveOrder: true });
  } catch (err) {
    return {
        status: 'ERROR',
        errorId: 'getPagesBy_id err',
        err,
    };
  }

  return response.map(entity => entity.plain());
};
```

cheers!
