### ISSUE TITLE
Possible bug with array properties showing indexed (but the contents show excludedFromIndexes

### ISSUE THREAD

**Issue by DaveyEdwards** [sebelga/gstore-node#73]
Can't find any effect of this.  Model shows excludeFromIndexes
![image](https://user-images.githubusercontent.com/15203899/29011818-fd5fddbc-7aea-11e7-8e67-0678879c4173.png)

The field shows that it is indexed.  (No other properties falsely show it)
![image](https://user-images.githubusercontent.com/15203899/29011798-c68208e2-7aea-11e7-8ee8-a490bea391e5.png)

But then its values all state not indexed.  (Note the array content type)
![image](https://user-images.githubusercontent.com/15203899/29011830-1c1ddc7c-7aeb-11e7-93c7-e12f7c7bfd50.png)

Not sure if its anything to pay attention to as it is __not__ stored in the indexs (n0deEdge).
The note above showed that the content type of n0deEdge is an array (which is correct), and below it shows it is a string.
![image](https://user-images.githubusercontent.com/15203899/29012006-ca6a294c-7aec-11e7-8702-908bdbea4edb.png)

**Comment by sebelga** [comment]
Hello,

For the "type" that does not seem to match in the "Edit property" screen and the Dashboard view, it is something on Google (or maybe google-cloud-node) as the only thing that gstore-node does is validate the type "array" and to let or no save the entity.
It saves with the following format:

```js
{
    name: 'nameOfProp',
    value: yourArray,
    excludeFromIndexes: true/false,
}
```
Like mentioned here: https://googlecloudplatform.github.io/google-cloud-node/#/docs/datastore/master/datastore?method=save

You can ask on google-cloud-node for more info. 
Let me know if there is anything you find out. thank! 👍

**Comment by DaveyEdwards** [comment]
Ok thank you I will make a post on there.
