### ISSUE TITLE
Cannot find source of docs

### ISSUE THREAD

**Issue by steren** [sebelga/gstore-node#79]
I'd like to send documentation improvements, but cannot find where it is stored in this repo.

The code for `// from inside a Transaction` in https://sebelga.gitbooks.io/gstore-node/content/model/update-method.html is missing an `{`.

**Comment by sebelga** [comment]
Hello,
You should be able to comment on gitbook. Never used the feature but on each line (passing your mouse on the right) there is a "plus" sign to add comment.
thanks for the feedback I will look into it.

**Comment by steren** [comment]
Thanks for the reply. Is it stored somewhere on GitHub too? 
It could make sense to have it in a folder of the library.

**Comment by sebelga** [comment]
I will have a look into gitbook to see how it is possible to put the source code on github. I quickly looked the other day but could not find how.

**Comment by sebelga** [comment]
Hello
I finally looked at this and connected github to gitbook. Here is the repo for the docs
https://github.com/sebelga/gstore-node-docs
Better late than never! 😄
