### ISSUE TITLE
Schema will not allow excludeFromIndexes for an array

### ISSUE THREAD

**Issue by mcdaid01** [sebelga/gstore-node#80]
const studentSchema = new Schema({
	name: { joi: Joi.string().required() },
	scores:{ joi: Joi.array().required(), excludeFromIndexes: true } 
})

I get this error

{ Error: Exclude from indexes cannot be set on a list value
    at /Users/Mike/dev/current/datastore/node_modules/grpc/src/node/src/client.js:554:15 code: 400, metadata: Metadata { _internal_repr: {} } }

**Comment by sebelga** [comment]
It seems to be a change in the google-cloud library.  I have asked in their github:
https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2615#issuecomment-338663518
I'll keep you posted. thanks for reporting :+1:

**Comment by mcdaid01** [comment]
Thanks for the quick update, I have no problem doing it this way without using gstore-node

const Datastore = require('@google-cloud/datastore')
const projectId = 'nodejs-1stgo'
const datastore = Datastore({ projectId })

const key = datastore.key(['Student'])
const data = [{
	name:'user',
	value:'Mike'
}, {
	name:'scores',
	value: [23, 40, 50],
	excludeFromIndexes: true
}]
datastore.save({ key, data }).then((res) => console.log(res))

**Comment by sebelga** [comment]
Oh, ok, let me have a look into it then.

**Comment by sebelga** [comment]
Hello,
Can you confirm that it is working with version **1.1.0** of @google-cloud/datastore? As they made a change between 1.0.0 and 1.1.0.
thanks

**Comment by sebelga** [comment]
@mcdaid01 I just release v2.0.2 that should fix this issue. Let me know if there is still a problem. 👍

**Comment by mcdaid01** [comment]
@sebelga it is all working correctly now. Thanks for the fix and a great library.
