### ISSUE TITLE
Updating a child with object type

### ISSUE THREAD

**Issue by zchodi** [sebelga/gstore-node#82]
hello, i have an entity with the ff model.
model
first_name: { type: 'string' },
  last_name: { type: 'string' },
  address: { type: 'object' },

and as I save, I save the address as 
{ number: 001, street: example street, City: example City }

AFTER I SAVE IT, i will update the City only... 

how should i do that? because as i update it, it will overwrite all the values with
street: { City: overwriteValuehere }

i want it instead street: { number: 001, street: example street, City: overwriteValuehere }

tnx!

**Comment by sebelga** [comment]
Hello,

For you use case you need to first fetch the entity before being able to update the address. You could write a custom function for that like this:

```js
const schema = new Schema(
    first_name: { ... },
    last_name: { ... },
    address: { ... }, 
);

schema.methods.updateAddress = function updateAddress(address) {
    // the scope (this) is the entity instance
    return this.datastoreEntity() // helper to fetch the entity
        .then((entity) => {
            entity.entityData = Object.assign({}, entity.entityData, address);
            return entity.save();
        });
};
```

```js
// in some controller
const User  = require('./user.model');

const user = new User(null, 123); // 123 is the id to update
user.updateAddress({ city: 'Madrid' }).then(() => {)

```

**Comment by sebelga** [comment]
Closing for no update.
Feel free to reopen for any question.
