### ISSUE TITLE
excludeFromIndexes doesn't work

### ISSUE THREAD

**Issue by phantomlinux** [sebelga/gstore-node#83]
Hi, would like to know if anyone face this issue? All my properties default to Indexed even after I set excludeFromIndexes to true. Below is my schema and datastore gui.
 
![screen shot 2017-12-06 at 4 20 26 pm](https://user-images.githubusercontent.com/12216382/33651696-c0d57bb0-daa1-11e7-931d-863a013676cb.png)

<img width="321" alt="screen shot 2017-12-06 at 4 21 10 pm" src="https://user-images.githubusercontent.com/12216382/33651704-c5958ba4-daa1-11e7-8f38-6d13e5878d51.png">

**Comment by sebelga** [comment]
Hi,
This is quiet strange indeed. Can you provide your full schema so I can test it on my side?

Also, you don't need to declare "explicityOnly: true" it is the default.
And you probably don't want the "createdAt" default to defaultValues.NOW as that means that each time the entity is saved the createdAt will be updated. You only wants to set it when you create an entity.

**Comment by phantomlinux** [comment]
<img width="669" alt="screen shot 2017-12-07 at 10 28 23 am" src="https://user-images.githubusercontent.com/12216382/33696248-509f0820-db3c-11e7-9a4b-022fab6a1c59.png">
<img width="1183" alt="screen shot 2017-12-07 at 10 36 37 am" src="https://user-images.githubusercontent.com/12216382/33696256-574c4a98-db3c-11e7-8fc4-b29a29c6fdeb.png">

Thanks for replying me. This is my feathers create function. 
Still new to node.js... Not really know how to debug, but I did put some breakpoints in the lib files and traced the object... It reaches the end and excludeFromIndexes is still recorded with the 4 fields I have.
these are 2 more screenshots, hope it's useful.

**Comment by sebelga** [comment]
Hello,
can you confirm that you have the dependency of "@google-cloud/datastore": "1.1.0" or superior?
thanks

**Comment by phantomlinux** [comment]
"@google-cloud/datastore": "^1.1.0",
"gstore-node": "^2.0.2",

**Comment by sebelga** [comment]
It is strange indeed. I need to make some test with you Schema. Unfortunately I cannot until beginning of next week.
For Objects and Arrays the actual "not indexed" appears when you "edit" the entity in the datastore gui.

**Comment by phantomlinux** [comment]
It's really strange. I just tried to create another Schema again, with only name:'string', and another object field. Is it supposed to be like that? It stated indexed, but there's no way to uncheck at the gui. Is there problem with Datastore itself? 

<img width="776" alt="screen shot 2017-12-07 at 10 03 52 pm" src="https://user-images.githubusercontent.com/12216382/33719081-9a388db8-db9a-11e7-8319-7f65dce9896a.png">
<img width="768" alt="screen shot 2017-12-07 at 10 04 02 pm" src="https://user-images.githubusercontent.com/12216382/33719094-a32702ce-db9a-11e7-9fb2-51f7f44a2b03.png">

I would try to look for the problem in the meantime. Thank you so much!

**Comment by phantomlinux** [comment]
I know there's the array excludeFromIndexes issue going on though... I'll try to debug and test, thanks

**Comment by sebelga** [comment]
I have been making some tests and effectively it does not work anymore as expected. I know the google-cloud team has been making some changes in the exludeFromIndexes syntax and a few issues are opened on their side. Even their documentation "master" differs from the "1.1.0" documentation on the subject.

If you want to open another issue on their side, here is the entity payload generated by gstore-node that does not exclude from indexes as it should:

```
{
    "key": {
        "namespace": "my.namespace",
        "kind": "MyEntity",
        "path": [
            "MyEntity",
            null
        ]
    },
    "data": [
        {
            "name": "systems",
            "value": {
                "a": "123c",
                "b": "456c"
            }
        },
        {
            "name": "phoneNumber",
            "value": "0123456789"
        },
        {
            "name": "createdAt",
            "value": "2017-12-12T06:16:35.145Z"
        }
    ],
    "excludeFromIndexes": [
        "phoneNumber",
        "systems",
        "createdAt",
        "systems.a",
        "systems.b"
    ]
}
```

**Comment by phantomlinux** [comment]
hi @sebelga , thank you so much for this. Will keep track on the issue u created in their repo.

**Comment by sebelga** [comment]
Hi @phantomlinux. It seems that the issue is fixed on google cloud side. I updated gstore to make it work (v 2.1.3). Make sure to have the latest google-cloud/datastore version (1.3.3). Let me know if the problem persists, thanks! 👍

**Comment by phantomlinux** [comment]
Work like a charm now @sebelga ! thanks!
