### ISSUE TITLE
Support for named keys

### ISSUE THREAD

**Issue by beaulac** [sebelga/gstore-node#84]
Are there any plans to add support for named keys? It seems that `createKey` is always expecting ID to either be a numeric string or number, but I would like to be able to create an entity that builds keys using the string without parsing it. It would be nice to define the type of key when defining a schema.

On a related note, since the ID is being parsed with `parseInt`, IDs that are larger than 2<sup>53</sup> -1 will not parse properly 😢 . This could be a problem for anyone looking to interoperate with IDs generated from languages that properly support 64-bit integers. Instead of parsing as JS numbers, they should be wrapped with `datastore.int()`.

**Comment by sebelga** [comment]
Hello,
What to you mean by "named key" ? Can you give me an example?

I will look into what you comment about parsing 64 bit integer, thanks for the info!

**Comment by sebelga** [comment]
Hi,
Latest realease (v2.1.0) should fix both of the issues. Let me know how it goes on your side.
Thanks!

**Comment by sebelga** [comment]
Hi
Latest release (v2.1.0) should fix both of the issue. Let me know how it goes on your side.
Thanks!
