### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by nexussmart** [sebelga/gstore-node#89]
Hello,

First of all thank you for your work.
I would have liked to know if you will soon migrate to typescript?

Thank you in advance

**Comment by sebelga** [comment]
Hello,
Although this would be a nice feature, this is not currently planned in future releases. I guess you are mainly interested in getting all the typings for your project?

It would be nice to know what is the interest for Typescript support. Let's leave this issue opened and find out :smile:

**Comment by kirillgroshkov** [comment]
We also need TS support. Well, it serves as documentation, it allows to use IntelliSense, and fits well in the project that is already using Typescript everywhere.

I can see that Google in their different APIs are moving faster and faster with adopting Typescript and providing typings inside libraries (Firebase, for example, many others too, but not `datastore` itself yet).

If to narrow down to 1 argument:

It serves as documentation, sometimes better than documentation itself.

**Comment by sebelga** [comment]
Ok I take note. I am currently finishing a big feature (cache mechanism) for the next release (v3.0.0)
Typescript might then be a next target.

**Comment by kirillgroshkov** [comment]
Sounds good! Good luck with 3.0!

**Comment by sebelga** [comment]
Hello..
Could you point me to a few good node library that you use that are made in Typescript? So I can have a look at how they package and expose their lib.
thanks!

**Comment by LogansUA** [comment]
@sebelga here's [repository](https://github.com/DefinitelyTyped/DefinitelyTyped) for typescript types.
For examples you can check the [@types/express](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/express) or [@types/node](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node)

**Comment by sebelga** [comment]
Hi @LogansUA thanks but I was referring to NodeJS **libraries** you are using in your projects done in Typescript. So I can have a look at how they expose their bundles. (both in es6 and Typescript format). :+1:

**Comment by LogansUA** [comment]
Well, I'm now using express, dotenv, ramda in my TS project with their typescript types

**Comment by sebelga** [comment]
Yes that might be a solution. Just writing the type definitions files :smile:  I was thinking in converting the whole project from js to Typescript but might not be necessary. I will give it a thought.

**Comment by sebelga** [comment]
Hello,
I finished writing the typings for gstore-node. I haven't published it yet as I would like if someone could test it in a actual Typescript project. I hope I haven't forgot anything 😄

@LogansUA @nexussmart @kirillgroshkov could one of you test this inside your project?

Just clone the "feature/#89-typescript-definitions" branch and replace the content in the `node_modules/gstore-node` folder.

This is how to add the Types for a User Model

```ts
type UserTypes = {
    userName: string; // mandatory
    email: string; // mandatory
    age?: number;
    tags?: string[];
    birthday?: Date;
}

// Strict typings (not other properties allowed than the ones on Schema)
// ----------------------------------------------------------------------------------
const schema = new Schema<UserTypes>({
    userName: { type: 'string' },
    email: { type: 'string' },
    age: { type: 'int' },
    tags: { type: 'array' },
    birthday: { type: 'datetime' },
    unknownNotAllowed: {} // this should give a ts error
});

const User = gstore.model<UserTypes>('User', schema);

// Strict typings + other properties allowed
// ----------------------------------------------------------------------------------
const schema = new Schema<UserTypes>({
    userName: { type: 'string' },
    email: {},
    age: {},
    tags: {},
    birthday: {},
    unknownNotAllowed: {} // this should give a ts error
}, { explicitOnly: false });

// Allow "other" properties on the entities
const User = gstore.model<UserTypes & {[propName: string]: any}>('User', schema);

// No Tyings on schemas (what you have now that should still work)
// ----------------------------------------------------------------------------------
const schema = new Schema({
    userName: { type: 'string' },
    email: {},
    age: {},
    tags: {},
    birthday: {},
    unknownAllowed: {} // this should *not* give a ts error
}, { explicitOnly: false });

const User = gstore.model('User', schema);
```

**Comment by sebelga** [comment]
Hello,
I just made a release (v4.1.0) with Typescript support. Let me know if it works for you 👍

**Comment by kirillgroshkov** [comment]
Great, thanks! I'll get back when we actually try and start using it. But good to know that we have types now!
