### ISSUE TITLE
Return Key datastore using nodejs

### ISSUE THREAD

**Issue by DerlysF** [sebelga/gstore-node#93]
I am not able to pull of the kind and make a res.json using gcloud beta deploy functions, is there any way to do?

`exports.listar = (req, res) => {
var query = ds.createQuery("pessoa", "Testando");
query.run(function (err, entities) {

    var keys = entities.map(function (entity) {
        // datastore.KEY is a Symbol
        return entity[ds.KEY];
    });
});
};`

**Comment by sebelga** [comment]
Are you using gstore-node?

**Comment by DerlysF** [comment]
yes, but I need to implement this with google cloud functions

**Comment by sebelga** [comment]
Well in your code there is no gstore.
Could you share the whole function file?

**Comment by DerlysF** [comment]
I have a simple system of login and register , using nodejs with passportjs, the authentication work´s local, but what I need is that my authentication work´s with Google Cloud Functions, and my system in local, my system send a request for google cloud functions and return user 
authenticated

**Comment by gcPeterJaeger** [comment]
seems that you are struggling with passport.js and not with gstore. The original democode for passport makes use of mongoose and MongoDB as a backend for user admin. 
May be should better describe what the real issue is ? Doing a auth strategie for g+ ? seralizing the authenticated user ? or using gstore ?

**Comment by sebelga** [comment]
I will close this issue for now. If you need some inspiration as to how to get started, I created a demo application, check the repo: https://github.com/sebelga/google-datastore-blog-app
